import pg from 'pg';
const {Pool}=pg;const db=new Pool({connectionString:process.env.DATABASE_URL});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function fieldMatch(v,s,min,max){if(s==='*')return true;for(const part of s.split(',')){if(part.startsWith('*/')){const n=Number(part.slice(2));if(n>0&&(v-min)%n===0)return true}else if(/^\d+$/.test(part)&&Number(part)===v)return true}return false}
function cronMatch(expr,d){const p=expr.trim().split(/\s+/);if(p.length!==5)return false;return fieldMatch(d.getUTCMinutes(),p[0],0,59)&&fieldMatch(d.getUTCHours(),p[1],0,23)&&fieldMatch(d.getUTCDate(),p[2],1,31)&&fieldMatch(d.getUTCMonth()+1,p[3],1,12)&&fieldMatch(d.getUTCDay(),p[4],0,6)}
function nextRun(expr,from=new Date()){const d=new Date(from);d.setUTCSeconds(0,0);d.setUTCMinutes(d.getUTCMinutes()+1);for(let i=0;i<525600;i++){if(cronMatch(expr,d))return d;d.setUTCMinutes(d.getUTCMinutes()+1)}throw new Error('Cron did not produce a run within one year')}
async function callNode(row,path,body){const base=(row.base_url||process.env.CRAKNODE_URL||'http://localhost:8088').replace(/\/$/,'');const token=row.api_token||process.env.CRAKNODE_TOKEN||'';const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${token}`},body:JSON.stringify(body||{})});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(data.error||`CrakNode ${r.status}`);return data}
async function runSchedule(s){const id=s.identifier;switch(s.action){case'start':case'stop':case'restart':await callNode(s,`/v1/servers/${id}/action`,{action:s.action});break;case'command':if(!s.payload)throw new Error('Command schedule has no payload');await callNode(s,`/v1/servers/${id}/command`,{command:s.payload});break;case'backup':{const b=await db.query("insert into backups(server_id,name,status) values($1,$2,'CREATING') returning id",[s.server_id,`Scheduled ${new Date().toISOString()}`]);try{const n=await callNode(s,`/v1/servers/${id}/backup`,{backupId:b.rows[0].id});await db.query("update backups set status='READY',size_bytes=$2,remote_path=$3 where id=$1",[b.rows[0].id,n.size||0,n.path||''])}catch(e){await db.query("update backups set status='FAILED' where id=$1",[b.rows[0].id]);throw e}break}default:throw new Error('Unsupported schedule action')}}
async function tick(){const now=new Date();const {rows}=await db.query(`select sc.*,s.identifier,s.owner_id,n.base_url,n.api_token from schedules sc join servers s on s.id=sc.server_id left join nodes n on n.id=s.node_id where sc.enabled=true order by sc.created_at limit 200`);for(const s of rows){try{if(!s.next_run_at){await db.query('update schedules set next_run_at=$2 where id=$1',[s.id,nextRun(s.cron,now)]);continue}if(new Date(s.next_run_at)>now)continue;await runSchedule(s);const nr=nextRun(s.cron,now);await db.query("update schedules set last_run_at=now(),next_run_at=$2,run_count=run_count+1,failure_count=0,last_error='' where id=$1",[s.id,nr]);await db.query("insert into audit_events(event,subject_type,subject_id,metadata) values('schedule.run','server',$1,$2::jsonb)",[s.server_id,JSON.stringify({schedule:s.id,action:s.action})]);await db.query("insert into notifications(user_id,title,body,kind) values($1,$2,$3,'success')",[s.owner_id,`Schedule completed: ${s.name}`,`${s.action} ran on ${s.identifier}`])}catch(e){const msg=String(e?.message||e).slice(0,800);await db.query('update schedules set failure_count=failure_count+1,last_error=$2,next_run_at=$3 where id=$1',[s.id,msg,nextRun(s.cron,now)]).catch(()=>{});await db.query("insert into notifications(user_id,title,body,kind) values($1,$2,$3,'error')",[s.owner_id,`Schedule failed: ${s.name}`,msg]).catch(()=>{});console.error('[schedule]',s.name,msg)}}}

async function billingTick(){
  const {rows}=await db.query(`select s.*,p.price_monthly,p.currency,p.name plan_name,u.credits,n.base_url,n.api_token from servers s join plans p on p.id=s.plan_id join users u on u.id=s.owner_id left join nodes n on n.id=s.node_id where s.next_due_at is not null and s.next_due_at<=now() and s.billing_status in ('ACTIVE','SUSPENDED') order by s.next_due_at limit 50`);
  for(const s of rows){const price=Number(s.price_monthly),credits=Number(s.credits);try{
    if(credits>=price){const c=await db.connect();try{await c.query('begin');const f=await c.query('select credits from users where id=$1 for update',[s.owner_id]);if(Number(f.rows[0].credits)<price){await c.query('rollback');continue}await c.query('update users set credits=credits-$2 where id=$1',[s.owner_id,price]);await c.query(`insert into wallet_transactions(user_id,amount,type,description,reference_type,reference_id) values($1,$2,'DEBIT',$3,'server',$4)`,[s.owner_id,-price,`Renewal: ${s.name}`,s.id]);const num=`INV-${Date.now().toString(36).toUpperCase()}-${s.id.slice(0,6).toUpperCase()}`;await c.query(`insert into invoices(user_id,number,amount,currency,status,due_at,paid_at,description) values($1,$2,$3,$4,'PAID',now(),now(),$5)`,[s.owner_id,num,price,s.currency,`${s.plan_name} renewal - ${s.name}`]);await c.query(`update servers set next_due_at=greatest(next_due_at,now())+interval '30 days',billing_status='ACTIVE',suspended=false,suspended_at=null,updated_at=now() where id=$1`,[s.id]);await c.query('commit')}catch(e){await c.query('rollback');throw e}finally{c.release()}if(s.suspended){await callNode(s,`/v1/servers/${s.identifier}/action`,{action:'start'}).catch(()=>{})}await db.query("insert into notifications(user_id,title,body,kind) values($1,'Service renewed',$2,'success')",[s.owner_id,`${s.name} renewed for ${s.currency} ${price}`]);
    }else{if(!s.suspended){await callNode(s,`/v1/servers/${s.identifier}/action`,{action:'stop'}).catch(()=>{});await db.query(`update servers set suspended=true,suspended_at=now(),billing_status='SUSPENDED',status='offline',updated_at=now() where id=$1`,[s.id]);const num=`INV-${Date.now().toString(36).toUpperCase()}-${s.id.slice(0,6).toUpperCase()}`;await db.query(`insert into invoices(user_id,number,amount,currency,status,due_at,description) values($1,$2,$3,$4,'DUE',now(),$5) on conflict(number) do nothing`,[s.owner_id,num,price,s.currency,`${s.plan_name} renewal - ${s.name}`]);await db.query("insert into notifications(user_id,title,body,kind) values($1,'Service suspended',$2,'error')",[s.owner_id,`${s.name} was suspended because wallet credits are insufficient.`])}}
  }catch(e){console.error('[billing]',s.identifier,String(e?.message||e))}}
}
async function main(){console.log('CrakHost Worker v0.10 started');for(;;){try{await tick();await billingTick()}catch(e){console.error('[worker]',e)}await sleep(30000)}}
main().catch(e=>{console.error(e);process.exit(1)});
