import {db} from './db';
import {updaterAgentRequest} from './updater-agent';

export type Severity='critical'|'warning'|'info';
export type AlertItem={key:string;severity:Severity;category:string;title:string;detail:string;createdAt:string;href:string};
export type NotificationSettings={emailEnabled:boolean;recipients:string[];criticalOnly:boolean;sendResolved:boolean;repeatHours:number;suppressDuringMaintenance:boolean;diskWarning:number;diskCritical:number;memoryWarning:number;memoryCritical:number;cpuCritical:number;nodeWarningSeconds:number;nodeCriticalSeconds:number;stalledOrderMinutes:number};
export const DEFAULT_NOTIFICATION_SETTINGS:NotificationSettings={emailEnabled:false,recipients:[],criticalOnly:true,sendResolved:true,repeatHours:6,suppressDuringMaintenance:true,diskWarning:80,diskCritical:90,memoryWarning:80,memoryCritical:90,cpuCritical:95,nodeWarningSeconds:90,nodeCriticalSeconds:180,stalledOrderMinutes:30};
function num(v:any,d:number,min:number,max:number){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d}
export function normalizeNotificationSettings(raw:any):NotificationSettings{const r=raw&&typeof raw==='object'?raw:{};return{emailEnabled:r.emailEnabled===true,recipients:Array.isArray(r.recipients)?r.recipients.map((x:any)=>String(x).trim().toLowerCase()).filter((x:string)=>/^\S+@\S+\.\S+$/.test(x)).slice(0,12):[],criticalOnly:r.criticalOnly!==false,sendResolved:r.sendResolved!==false,repeatHours:num(r.repeatHours,6,1,72),suppressDuringMaintenance:r.suppressDuringMaintenance!==false,diskWarning:num(r.diskWarning,80,50,98),diskCritical:num(r.diskCritical,90,60,99),memoryWarning:num(r.memoryWarning,80,50,98),memoryCritical:num(r.memoryCritical,90,60,99),cpuCritical:num(r.cpuCritical,95,60,100),nodeWarningSeconds:num(r.nodeWarningSeconds,90,30,600),nodeCriticalSeconds:num(r.nodeCriticalSeconds,180,60,1800),stalledOrderMinutes:num(r.stalledOrderMinutes,30,5,1440)}}
export async function getNotificationSettings(){const {rows}=await db.query(`select value from system_settings where key='notification_settings' limit 1`);return normalizeNotificationSettings(rows[0]?.value||{})}
function iso(value:any){const d=new Date(value||Date.now());return Number.isFinite(d.getTime())?d.toISOString():new Date().toISOString()}
function number(value:any){const n=Number(value);return Number.isFinite(n)?n:0}
function severityRank(value:Severity){return value==='critical'?0:value==='warning'?1:2}

export async function evaluateAlerts(includeHost=true){
  const settings=await getNotificationSettings();
  const [nodesQ,failedQ,stuckQ,ticketsQ,backupsQ,operationsQ]=await Promise.all([
    db.query(`select id,name,location,enabled,last_seen_at from nodes where enabled=true order by name`),
    db.query(`select count(*)::int count,max(updated_at) latest from orders where status='FAILED' and updated_at>=now()-interval '24 hours'`),
    db.query(`select count(*)::int count,min(updated_at) oldest from orders where status in ('PAID','PROVISIONING') and updated_at<now()-($1::int*interval '1 minute')`,[settings.stalledOrderMinutes]),
    db.query(`select count(*)::int count,count(*) filter(where priority='URGENT')::int urgent,max(updated_at) latest from support_tickets where status<>'CLOSED' and priority in ('HIGH','URGENT')`),
    db.query(`select count(*)::int count,max(created_at) latest from backups where status='FAILED' and created_at>=now()-interval '24 hours'`),
    db.query(`select value from system_settings where key='operations'`)
  ]);
  const alerts:AlertItem[]=[];const now=Date.now();
  for(const node of nodesQ.rows){const last=node.last_seen_at?new Date(node.last_seen_at).getTime():0;const age=last?Math.max(0,(now-last)/1000):Number.POSITIVE_INFINITY;if(!last||age>settings.nodeCriticalSeconds)alerts.push({key:`node:${node.id}:offline`,severity:'critical',category:'node',title:`${node.name} is offline`,detail:last?`No heartbeat for ${Math.floor(age/60)} minutes · ${node.location||'Unknown location'}`:`No heartbeat has been recorded · ${node.location||'Unknown location'}`,createdAt:last?iso(node.last_seen_at):new Date().toISOString(),href:'/nodes'});else if(age>settings.nodeWarningSeconds)alerts.push({key:`node:${node.id}:degraded`,severity:'warning',category:'node',title:`${node.name} heartbeat is delayed`,detail:`Last heartbeat ${Math.floor(age)} seconds ago · ${node.location||'Unknown location'}`,createdAt:iso(node.last_seen_at),href:'/nodes'})}
  const failed=failedQ.rows[0]||{};if(number(failed.count)>0)alerts.push({key:'orders:failed24',severity:'critical',category:'provisioning',title:`${number(failed.count)} provisioning failure${number(failed.count)===1?'':'s'} in 24h`,detail:'Failed orders need review before retrying or refunding customer credit.',createdAt:iso(failed.latest),href:'/admin/orders'});
  const stuck=stuckQ.rows[0]||{};if(number(stuck.count)>0)alerts.push({key:'orders:stuck',severity:'warning',category:'provisioning',title:`${number(stuck.count)} order${number(stuck.count)===1?'':'s'} stalled in provisioning`,detail:`Paid or provisioning orders have not changed state for more than ${settings.stalledOrderMinutes} minutes.`,createdAt:iso(stuck.oldest),href:'/admin/orders'});
  const tickets=ticketsQ.rows[0]||{};if(number(tickets.count)>0)alerts.push({key:'support:priority',severity:number(tickets.urgent)>0?'critical':'warning',category:'support',title:`${number(tickets.count)} high-priority support ticket${number(tickets.count)===1?'':'s'} open`,detail:number(tickets.urgent)>0?`${number(tickets.urgent)} marked URGENT.`:'HIGH priority tickets are waiting for staff attention.',createdAt:iso(tickets.latest),href:'/support'});
  const backups=backupsQ.rows[0]||{};if(number(backups.count)>0)alerts.push({key:'backups:failed24',severity:'warning',category:'backup',title:`${number(backups.count)} backup failure${number(backups.count)===1?'':'s'} in 24h`,detail:'Review failed backup jobs before the next retention window.',createdAt:iso(backups.latest),href:'/backups'});
  const operations=operationsQ.rows[0]?.value||{};if(operations?.maintenanceMode===true)alerts.push({key:'maintenance:enabled',severity:'info',category:'maintenance',title:'Maintenance mode is enabled',detail:String(operations.maintenanceMessage||'Scheduled maintenance in progress.').slice(0,240),createdAt:new Date().toISOString(),href:'/operations'});
  if(includeHost){try{const result=await updaterAgentRequest('/metrics');const host:any=result.data||{};const disk=number(host.disk?.percent),memory=number(host.memory?.percent),cpu=number(host.cpu_percent);if(disk>=settings.diskCritical)alerts.push({key:'host:disk:critical',severity:'critical',category:'host',title:`Root disk is ${disk.toFixed(1)}% used`,detail:'Free storage is critically low. Run safe cleanup or expand the VPS disk.',createdAt:new Date().toISOString(),href:'/deployment'});else if(disk>=settings.diskWarning)alerts.push({key:'host:disk:warning',severity:'warning',category:'host',title:`Root disk is ${disk.toFixed(1)}% used`,detail:'Disk pressure is elevated. Review Docker cache and backup retention.',createdAt:new Date().toISOString(),href:'/deployment'});if(memory>=settings.memoryCritical)alerts.push({key:'host:memory:critical',severity:'critical',category:'host',title:`Memory usage is ${memory.toFixed(1)}%`,detail:'Host memory pressure is critical and may affect workloads.',createdAt:new Date().toISOString(),href:'/operations'});else if(memory>=settings.memoryWarning)alerts.push({key:'host:memory:warning',severity:'warning',category:'host',title:`Memory usage is ${memory.toFixed(1)}%`,detail:'Host memory pressure is elevated.',createdAt:new Date().toISOString(),href:'/operations'});if(cpu>=settings.cpuCritical)alerts.push({key:'host:cpu:critical',severity:'critical',category:'host',title:`CPU usage is ${cpu.toFixed(1)}%`,detail:'Sustained CPU saturation can delay control-plane and customer workloads.',createdAt:new Date().toISOString(),href:'/operations'})}catch(error){alerts.push({key:'host:agent:unavailable',severity:'warning',category:'host',title:'Host telemetry agent is unavailable',detail:error instanceof Error?error.message:'The privileged updater agent could not be reached.',createdAt:new Date().toISOString(),href:'/deployment'})}}
  alerts.sort((a,b)=>severityRank(a.severity)-severityRank(b.severity)||new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());
  return{alerts,settings,maintenanceMode:operations?.maintenanceMode===true};
}
