'use client';
import Link from 'next/link';
import {BadgeCheck,Loader2,MailCheck,RefreshCw} from 'lucide-react';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
const LOGO='https://i.ibb.co/sv3BkwyS/logo-Photoroom.png';

export default function VerifyEmail(){
 const r=useRouter();const started=useRef(false);const[email,setEmail]=useState(''),[otp,setOtp]=useState(''),[next,setNext]=useState('/dashboard'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(typeof window==='undefined'||started.current)return;started.current=true;const q=new URLSearchParams(window.location.search);const e=q.get('email')||'';const rawNext=q.get('next')||'/dashboard';const target=rawNext.startsWith('/')&&!rawNext.startsWith('//')?rawNext:'/dashboard';const token=q.get('token')||'';setEmail(e);setNext(target);if(token)void verify({token},target)},[]);
 async function verify(payload:{token?:string;email?:string;otp?:string},redirectTarget=next){setBusy('verify');setError('');setMessage('');try{const res=await fetch('/api/auth/verify-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await res.json();if(!res.ok)throw new Error(d.error||'Verification failed');setMessage('Email verified. Your secure session is ready.');setTimeout(()=>{r.push(redirectTarget);r.refresh()},700)}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function submit(e:FormEvent){e.preventDefault();if(!email)return setError('Enter your email address.');if(!/^[0-9]{6}$/.test(otp))return setError('Enter the 6-digit code.');await verify({email,otp},next)}
 async function resend(){if(!email)return setError('Enter your email address first.');setBusy('resend');setError('');setMessage('');try{const res=await fetch('/api/auth/verify-email/resend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,next})}),d=await res.json();if(!res.ok)throw new Error(d.error||'Unable to resend code');setMessage(d.message||'A new verification code was sent.')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <div className="authWrap"><form className="authBox" onSubmit={submit}><img className="authLogo49" src={LOGO} alt="CrakHost"/><div className="brand authBrand"><span>CRAK<span style={{color:'#a78bfa'}}>HOST</span></span></div><div className="authTitle">Verify your email</div><div className="authSub">Enter the 6-digit code from the CrakHost verification email. Verification links also work automatically.</div>{message&&<div className="notice"><BadgeCheck size={15} style={{verticalAlign:'middle'}}/> {message}</div>}{error&&<div className="notice error">{error}</div>}<div className="field"><label>Email address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com" required/></div><div className="field"><label>Verification code</label><input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" maxLength={6} style={{letterSpacing:6,fontSize:20,fontWeight:700}} required/></div><button className="btn authBtn" disabled={!!busy}>{busy==='verify'?<Loader2 size={15} className="spin"/>:<MailCheck size={15}/>} {busy==='verify'?'Verifying...':'Verify email'}</button><button type="button" className="btn" style={{width:'100%',marginTop:10}} onClick={resend} disabled={!!busy}><RefreshCw size={14}/>{busy==='resend'?'Sending...':'Resend verification code'}</button><div className="authFoot">Already verified? <Link href="/login">Sign in</Link></div></form></div>
}
