'use client';
import Link from 'next/link';
import {BadgeCheck,KeyRound,Loader2,Zap} from 'lucide-react';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';

export default function ResetPassword(){
 const r=useRouter();const[token,setToken]=useState(''),[email,setEmail]=useState(''),[otp,setOtp]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(typeof window==='undefined')return;const q=new URLSearchParams(window.location.search);setToken(q.get('token')||'');setEmail(q.get('email')||'')},[]);
 async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');if(password.length<10)return setError('Password must be at least 10 characters.');if(password!==confirm)return setError('Passwords do not match.');if(!token&&(!email||!/^[0-9]{6}$/.test(otp)))return setError('Enter your email and the 6-digit reset code.');setBusy(true);try{const res=await fetch('/api/auth/password/reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,email,otp,password})}),d=await res.json();if(!res.ok)throw new Error(d.error||'Password reset failed');setMessage(d.message||'Password changed.');setTimeout(()=>{r.push('/login');r.refresh()},900)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="authWrap"><form className="authBox" onSubmit={submit}><div className="brand authBrand"><div className="brandMark"><Zap size={18}/></div>CrakHost</div><div className="authTitle">Reset password</div><div className="authSub">Use the secure reset link or the 6-digit OTP from your CrakHost email.</div>{message&&<div className="notice"><BadgeCheck size={14} style={{verticalAlign:'middle'}}/> {message}</div>}{error&&<div className="notice error">{error}</div>}{!token&&<><div className="field"><label>Email address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></div><div className="field"><label>Reset code</label><input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" maxLength={6} style={{letterSpacing:6,fontSize:20,fontWeight:700}} required/></div></>}<div className="field"><label>New password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} autoComplete="new-password" placeholder="Minimum 10 characters" required/></div><div className="field"><label>Confirm password</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={10} autoComplete="new-password" required/></div><button className="btn authBtn" disabled={busy}>{busy?<Loader2 size={15} className="spin"/>:<KeyRound size={15}/>} {busy?'Updating...':'Change password'}</button><div className="authFoot"><Link href="/forgot-password">Request another code</Link> · <Link href="/login">Sign in</Link></div></form></div>
}
