'use client';
import {useEffect,useMemo,useState} from 'react';
import {Ban,CheckCircle2,Coins,Plus,RefreshCw,Save,Server,Store,Trash2,UserRoundCog,Users} from 'lucide-react';

type Plan={id:string;slug:string;name:string;description:string;memory_mb:number;cpu_limit:string;disk_mb:number;price_monthly:string;currency:string;enabled:boolean;featured:boolean;sort_order:number;template_slug:string};
type Template={slug:string;name:string;game_type:string;enabled:boolean};
type User={id:string;name:string;email:string;role:string;credits:string;account_status:string;banned_at?:string;ban_reason?:string;server_count:number;order_count:number;created_at:string};
type Service={id:string;name:string;identifier:string;status:string;billing_status:string;suspended:boolean;owner_email:string;node_name:string;memory_mb:number;cpu_limit:string;disk_mb:number;primary_ip:string;primary_port:number;next_due_at?:string};

const emptyPlan={slug:'',name:'',description:'',memoryMb:2048,cpuLimit:1,diskMb:15000,priceMonthly:1490,currency:'LKR',templateSlug:'minecraft',sortOrder:100,featured:false,enabled:true};

export default function AdminCommerceCenter(){
 const[tab,setTab]=useState<'plans'|'customers'|'services'>('plans');
 const[plans,setPlans]=useState<Plan[]>([]),[templates,setTemplates]=useState<Template[]>([]),[users,setUsers]=useState<User[]>([]),[services,setServices]=useState<Service[]>([]);
 const[form,setForm]=useState<any>(emptyPlan),[editing,setEditing]=useState<string>(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[state,setState]=useState('all');
 const[transfer,setTransfer]=useState<Record<string,string>>({}),[banReason,setBanReason]=useState<Record<string,string>>({});
 async function json(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return{error:`HTTP ${r.status}`}}}
 async function load(){setBusy(true);setMsg('');try{const[p,u,s]=await Promise.all([fetch('/api/admin/plans',{cache:'no-store'}),fetch(`/api/admin/users?q=${encodeURIComponent(q)}&state=${encodeURIComponent(state)}`,{cache:'no-store'}),fetch('/api/admin/servers?limit=200',{cache:'no-store'})]);const[pd,ud,sd]=await Promise.all([json(p),json(u),json(s)]);if(!p.ok)throw new Error(pd.error||'Unable to load plans');if(!u.ok)throw new Error(ud.error||'Unable to load users');setPlans(pd.plans||[]);setTemplates(pd.templates||[]);setUsers(ud.users||[]);if(s.ok)setServices(sd.servers||[])}catch(e:any){setMsg(e.message||'Unable to load admin commerce data')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const stats=useMemo(()=>({enabledPlans:plans.filter(p=>p.enabled).length,activeUsers:users.filter(u=>u.account_status==='ACTIVE').length,banned:users.filter(u=>u.account_status==='BANNED').length,services:services.length}),[plans,users,services]);
 function editPlan(p:Plan){setEditing(p.id);setForm({slug:p.slug,name:p.name,description:p.description||'',memoryMb:Number(p.memory_mb),cpuLimit:Number(p.cpu_limit),diskMb:Number(p.disk_mb),priceMonthly:Number(p.price_monthly),currency:p.currency,templateSlug:p.template_slug,sortOrder:Number(p.sort_order),featured:!!p.featured,enabled:!!p.enabled});window.scrollTo({top:0,behavior:'smooth'})}
 function resetPlan(){setEditing('');setForm(emptyPlan)}
 async function savePlan(){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/plans',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,id:editing||undefined})});const d=await json(r);if(!r.ok)throw new Error(d.error||'Plan save failed');setMsg(editing?'Plan updated.':'Plan created.');resetPlan();await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function disablePlan(id:string){if(!confirm('Disable this plan? Existing services are not deleted.'))return;const r=await fetch('/api/admin/plans',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})}),d=await json(r);setMsg(r.ok?'Plan disabled.':d.error||'Unable to disable plan');if(r.ok)await load()}
 async function updateUser(u:User,patch:any){const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:u.id,...patch})}),d=await json(r);setMsg(r.ok?'Customer updated.':d.error||'Customer update failed');if(r.ok)await load()}
 async function removeUser(u:User){if(!confirm(`Delete ${u.email}? This is only allowed when the customer owns no active services.`))return;const r=await fetch('/api/admin/users',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:u.id})}),d=await json(r);setMsg(r.ok?'Customer account deleted and anonymized.':d.error||'Delete failed');if(r.ok)await load()}
 async function lifecycle(s:Service){const action=s.suspended?'unsuspend':'suspend';const r=await fetch(`/api/admin/servers/${encodeURIComponent(s.identifier)}/lifecycle`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})}),d=await json(r);setMsg(r.ok?`Service ${action} complete.`:d.error||'Service action failed');if(r.ok)await load()}
 async function transferService(s:Service){const email=(transfer[s.id]||'').trim();if(!email)return setMsg('Enter the destination customer email first.');const r=await fetch(`/api/admin/servers/${encodeURIComponent(s.identifier)}/transfer`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})}),d=await json(r);setMsg(r.ok?`Service transferred to ${d.owner||email}.`:d.error||'Transfer failed');if(r.ok){setTransfer(v=>({...v,[s.id]:''}));await load()}}
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">BUSINESS ADMINISTRATION</div><h1>Plans, customers & <span>services</span></h1><p>Create hosting plans, moderate customer accounts, inspect ownership and manage active customer services without touching database rows manually.</p></div><div className="heroActions"><button className="btn" onClick={load} disabled={busy}><RefreshCw size={14}/>{busy?'Refreshing':'Refresh'}</button></div></section>
  <section className="commerceGrid panelSection"><Metric label="Enabled plans" value={stats.enabledPlans} icon={<Store size={15}/>}/><Metric label="Active customers" value={stats.activeUsers} icon={<Users size={15}/>}/><Metric label="Banned" value={stats.banned} icon={<Ban size={15}/>}/><Metric label="Managed services" value={stats.services} icon={<Server size={15}/>}/></section>
  {msg&&<div className="notice panelSection">{msg}</div>}
  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2>Commerce workspace</h2><p>All values below come from the production database and service APIs.</p></div><div className="adminTabs"><button className={`btn ${tab==='plans'?'indigo':''}`} onClick={()=>setTab('plans')}>Plans</button><button className={`btn ${tab==='customers'?'indigo':''}`} onClick={()=>setTab('customers')}>Customers</button><button className={`btn ${tab==='services'?'indigo':''}`} onClick={()=>setTab('services')}>Services</button></div></div>
   {tab==='plans'&&<div><div className="releaseBox"><div className="panelSectionHead"><div><div className="sectionTitle"><Plus size={14}/> {editing?'Edit plan':'Create hosting plan'}</div><p>Resources, price, template, publishing and featured state.</p></div>{editing&&<button className="btn" onClick={resetPlan}>Cancel edit</button>}</div><div className="commerceForm"><input placeholder="slug" disabled={!!editing} value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><input placeholder="Plan name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.templateSlug} onChange={e=>setForm({...form,templateSlug:e.target.value})}>{templates.map(t=><option key={t.slug} value={t.slug}>{t.name} · {t.slug}</option>)}</select><input placeholder="Currency" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/><input type="number" min="512" placeholder="RAM MB" value={form.memoryMb} onChange={e=>setForm({...form,memoryMb:Number(e.target.value)})}/><input type="number" min="0.25" step="0.25" placeholder="vCPU" value={form.cpuLimit} onChange={e=>setForm({...form,cpuLimit:Number(e.target.value)})}/><input type="number" min="1000" placeholder="Disk MB" value={form.diskMb} onChange={e=>setForm({...form,diskMb:Number(e.target.value)})}/><input type="number" min="0" step="0.01" placeholder="Monthly price" value={form.priceMonthly} onChange={e=>setForm({...form,priceMonthly:Number(e.target.value)})}/><input className="wide" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input type="number" placeholder="Sort order" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/><label className="btn" style={{justifyContent:'center'}}><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><label className="btn" style={{justifyContent:'center'}}><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Published</label><button className="btn indigo" onClick={savePlan} disabled={busy}><Save size={13}/>{editing?'Save changes':'Create plan'}</button></div></div>
    <div className="commerceTable" style={{marginTop:14}}>{plans.map(p=><div className="commerceRow" key={p.id}><div><b>{p.name}</b><small>{p.slug} · {p.template_slug}</small></div><div>{p.currency} {Number(p.price_monthly).toLocaleString()}<small>/ 30 days</small></div><div>{Math.round(Number(p.memory_mb)/1024)} GB RAM<small>{Number(p.cpu_limit)} vCPU · {Math.round(Number(p.disk_mb)/1024)} GB disk</small></div><div><span className={`statusDot ${p.enabled?'active':'offline'}`}>{p.enabled?'PUBLISHED':'DISABLED'}</span><small>{p.featured?'Featured':'Standard'}</small></div><div className="adminActionGroup"><button className="btn" onClick={()=>editPlan(p)}>Edit</button>{p.enabled&&<button className="btn dangerBtn" onClick={()=>disablePlan(p.id)}><Trash2 size={12}/>Disable</button>}</div></div>)}{plans.length===0&&<div className="emptyState">No plans configured.</div>}</div></div>}
   {tab==='customers'&&<div><div className="commerceToolbar" style={{marginBottom:14}}><input style={{minWidth:260}} placeholder="Search name or email" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}}/><select value={state} onChange={e=>setState(e.target.value)}><option value="all">All states</option><option value="ACTIVE">Active</option><option value="BANNED">Banned</option><option value="DELETED">Deleted</option></select><button className="btn" onClick={load}>Search</button></div><div className="commerceTable">{users.map(u=><CustomerRow key={u.id} u={u} reason={banReason[u.id]||''} setReason={v=>setBanReason(x=>({...x,[u.id]:v}))} update={updateUser} remove={removeUser}/>)}{users.length===0&&<div className="emptyState">No customers match the current filter.</div>}</div></div>}
   {tab==='services'&&<div className="commerceTable">{services.map(s=><div className="commerceRow" key={s.id}><div><b>{s.name}</b><small>{s.identifier}:{s.primary_port} · {s.node_name||'No node'}</small></div><div>{s.owner_email}<small>{s.status} · {s.billing_status}</small></div><div>{Math.round(Number(s.memory_mb)/1024)} GB RAM<small>{Number(s.cpu_limit)} vCPU · {Math.round(Number(s.disk_mb||0)/1024)} GB disk</small></div><div><span className={`statusDot ${s.suspended?'offline':'active'}`}>{s.suspended?'SUSPENDED':'ACTIVE'}</span><small>{s.next_due_at?`Due ${new Date(s.next_due_at).toLocaleDateString()}`:'No due date'}</small></div><div className="adminActionGroup" style={{flexWrap:'wrap'}}><button className={`btn ${s.suspended?'successBtn':'dangerBtn'}`} onClick={()=>lifecycle(s)}>{s.suspended?<CheckCircle2 size={12}/>:<Ban size={12}/>} {s.suspended?'Unsuspend':'Suspend'}</button><input className="smallInput" style={{minWidth:190}} placeholder="new owner email" value={transfer[s.id]||''} onChange={e=>setTransfer(v=>({...v,[s.id]:e.target.value}))}/><button className="btn" onClick={()=>transferService(s)}>Transfer</button></div></div>)}{services.length===0&&<div className="emptyState">No managed services.</div>}</div>}
  </section>
 </>
}

function Metric({label,value,icon}:{label:string;value:any;icon:React.ReactNode}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span>{icon}</div><strong>{value}</strong></div>}
function CustomerRow({u,reason,setReason,update,remove}:{u:User;reason:string;setReason:(v:string)=>void;update:(u:User,p:any)=>Promise<void>;remove:(u:User)=>Promise<void>}){const[role,setRole]=useState(u.role),[credits,setCredits]=useState(String(u.credits));return <div className="commerceRow"><div><b>{u.name}</b><small>{u.email} · {u.account_status}</small></div><div>{u.server_count} services<small>{u.order_count} orders</small></div><div className="adminActionGroup"><select className="select compact" value={role} onChange={e=>setRole(e.target.value)}><option>USER</option><option>RESELLER</option><option>SUPPORT</option><option>ADMIN</option></select><input className="smallInput" type="number" style={{width:100}} value={credits} onChange={e=>setCredits(e.target.value)}/><button className="btn" onClick={()=>update(u,{role,credits})}><Coins size={12}/>Save</button></div><div>{u.account_status==='BANNED'?<span className="statusDot offline">BANNED</span>:u.account_status==='DELETED'?<span className="statusDot offline">DELETED</span>:<span className="statusDot active">ACTIVE</span>}<small>{u.ban_reason||new Date(u.created_at).toLocaleDateString()}</small></div><div className="adminActionGroup" style={{flexWrap:'wrap'}}>{u.account_status==='ACTIVE'&&<><input className="smallInput" placeholder="ban reason" value={reason} onChange={e=>setReason(e.target.value)}/><button className="btn dangerBtn" onClick={()=>update(u,{accountStatus:'BANNED',reason})}><Ban size={12}/>Ban</button></>}{u.account_status==='BANNED'&&<button className="btn successBtn" onClick={()=>update(u,{accountStatus:'ACTIVE'})}><UserRoundCog size={12}/>Unban</button>}{u.account_status!=='DELETED'&&<button className="btn dangerBtn" onClick={()=>remove(u)}><Trash2 size={12}/>Delete</button>}</div></div>}
