'use client';
import{useEffect,useState}from'react';
import{RefreshCw,Users,Server,Activity,Boxes,PauseCircle,PlayCircle,Plus,Network,ArrowRightLeft,ShieldCheck,Ban,UserCheck,Trash2,Save,PackageOpen,TicketCheck}from'lucide-react';

type U={id:string;name:string;email:string;role:string;credits:string;banned_at?:string|null;banned_reason?:string;server_count:number;order_count:number;email_verified_at?:string|null};
type S={id:string;name:string;identifier:string;status:string;billing_status:string;suspended:boolean;owner_email:string;node_name:string;memory_mb:number;cpu_limit:string;primary_port:number};
type P={id:string;slug:string;name:string;description:string;memory_mb:number;cpu_limit:string|number;disk_mb:number;price_monthly:string|number;currency:string;enabled:boolean;template_slug:string;featured:boolean;sort_order:number;service_count:number;order_count:number};
const blankPlan={slug:'',name:'',description:'',memory_mb:2048,cpu_limit:1,disk_mb:15000,price_monthly:1490,currency:'LKR',template_slug:'minecraft',featured:false,enabled:true,sort_order:100};

export default function AdminManager(){
 const[users,setUsers]=useState<U[]>([]),[servers,setServers]=useState<S[]>([]),[plans,setPlans]=useState<P[]>([]),[templates,setTemplates]=useState<any[]>([]),[infra,setInfra]=useState<any>({nodes:[],summary:{},migrations:[]}),[tab,setTab]=useState('overview'),[msg,setMsg]=useState(''),[overview,setOverview]=useState<any>({stats:{},audit:[]}),[loading,setLoading]=useState(true),[draft,setDraft]=useState<any>(blankPlan);
 async function load(){setLoading(true);setMsg('');try{const[u,s,o,t,i,p]=await Promise.all([fetch('/api/admin/users',{cache:'no-store'}),fetch('/api/admin/servers',{cache:'no-store'}),fetch('/api/admin/overview',{cache:'no-store'}),fetch('/api/admin/templates',{cache:'no-store'}),fetch('/api/admin/infrastructure',{cache:'no-store'}),fetch('/api/admin/plans',{cache:'no-store'})]);const[ud,sd,od,td,id,pd]=await Promise.all([u.json(),s.json(),o.json(),t.json(),i.json(),p.json()]);if(!u.ok)throw new Error(ud.error||'Admin access required');setUsers(ud.users||[]);if(s.ok)setServers(sd.servers||[]);if(o.ok)setOverview(od);if(t.ok)setTemplates(td.templates||[]);if(i.ok)setInfra(id);if(p.ok)setPlans(pd.plans||[])}catch(e:any){setMsg(e.message||'Unable to load admin data')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function updateUser(u:U,role:string,credits:string){const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:u.id,role,credits})});const d=await r.json();setMsg(r.ok?'User updated.':d.error||'Update failed');if(r.ok)void load()}
 async function moderate(u:U){const action=u.banned_at?'unban':'ban';if(!confirm(`${action==='ban'?'Disable':'Re-enable'} ${u.email}?`))return;const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:u.id,action,reason:'Disabled by administrator'})});const d=await r.json();setMsg(r.ok?(action==='ban'?'Account disabled and sessions revoked.':'Account re-enabled.'):d.error||'Moderation failed');if(r.ok)void load()}
 async function removeUser(u:U){if(!confirm(`Permanently delete ${u.email}? This is only allowed when no active services or orders remain.`))return;const r=await fetch(`/api/admin/users?id=${encodeURIComponent(u.id)}`,{method:'DELETE'}),d=await r.json();setMsg(r.ok?'User deleted.':d.error||'Delete failed');if(r.ok)void load()}
 async function createPlan(){const r=await fetch('/api/admin/plans',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)}),d=await r.json();setMsg(r.ok?'Plan published to the catalog.':d.error||'Plan creation failed');if(r.ok){setDraft(blankPlan);void load()}}
 async function savePlan(p:P){const r=await fetch('/api/admin/plans',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(p)}),d=await r.json();setMsg(r.ok?'Plan updated.':d.error||'Plan update failed');if(r.ok)void load()}
 async function removePlan(p:P){if(!confirm(`Delete plan ${p.name}? Active plans with services/orders cannot be deleted.`))return;const r=await fetch(`/api/admin/plans?id=${encodeURIComponent(p.id)}`,{method:'DELETE'}),d=await r.json();setMsg(r.ok?'Plan deleted.':d.error||'Delete failed');if(r.ok)void load()}
 async function transfer(s:S){const email=prompt('Transfer server to registered user email');if(!email)return;const r=await fetch(`/api/admin/servers/${s.identifier}/transfer`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})});const d=await r.json();setMsg(r.ok?`Server transferred to ${d.owner}.`:d.error||'Transfer failed');if(r.ok)void load()}
 async function lifecycle(s:S,action:string){const r=await fetch(`/api/admin/servers/${s.identifier}/lifecycle`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})});const d=await r.json();setMsg(r.ok?`Server ${action}ed.`:d.error||'Action failed');if(r.ok)void load()}
 async function drain(n:any){const r=await fetch(`/api/admin/nodes/${n.id}/drain`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({draining:!n.draining})});const d=await r.json();setMsg(r.ok?(d.draining?'Node placed in drain mode.':'Node returned to scheduler.'):d.error||'Drain update failed');if(r.ok)void load()}
 async function migrate(s:S){const options=(infra.nodes||[]).filter((n:any)=>n.name!==s.node_name&&!n.draining&&n.online);if(!options.length)return setMsg('No online non-draining target nodes are available.');const names=options.map((n:any,i:number)=>`${i+1}. ${n.name} (${n.location||'no location'})`).join('\n');const choice=prompt(`Target node number:\n${names}`);if(!choice)return;const target=options[Number(choice)-1];if(!target)return setMsg('Invalid target node selection.');const r=await fetch(`/api/admin/servers/${s.identifier}/migrate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({targetNodeId:target.id})});const d=await r.json();setMsg(r.ok?`Migration queued to ${target.name}.`:d.error||'Migration request failed');if(r.ok)void load()}
 async function addTemplate(){const slug=prompt('Template slug (example: paper)');if(!slug)return;const name=prompt('Display name',slug)||slug;const image=prompt('Docker image','itzg/minecraft-server:latest')||'';const r=await fetch('/api/admin/templates',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug,name,image,internalPort:25565,category:'Game Servers',environment:{EULA:'TRUE'},enabled:true})});const d=await r.json();setMsg(r.ok?'Template created.':d.error||'Template failed');if(r.ok)void load()}
 const summary=infra.summary||{};
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">ADMINISTRATION · v0.49</div><h1>Business <span>control center</span></h1><p>Manage real customers, plans, services, nodes, provisioning templates and support workflows from one live control-plane workspace.</p></div><div className="heroActions"><a className="btn" href="/support"><TicketCheck size={14}/>Ticket queue</a><button className="btn indigo" disabled={loading} onClick={load}><RefreshCw size={14}/>{loading?'Refreshing':'Refresh'}</button></div></section>
  <section className="adminOverview panelSection"><Metric label="Users" value={overview.stats?.users??0} icon={<Users size={15}/>}/><Metric label="Services" value={overview.stats?.servers??0} icon={<Server size={15}/>}/><Metric label="Running" value={overview.stats?.running??0} icon={<Activity size={15}/>}/><Metric label="Plans" value={plans.length} icon={<PackageOpen size={15}/>}/><Metric label="Nodes online" value={`${summary.online??0}/${summary.nodes??0}`} icon={<Boxes size={15}/>}/></section>
  {msg&&<div className="notice panelSection">{msg}</div>}
  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2>Admin workspace</h2><p>All counters and inventories below are read from production data.</p></div><div className="adminTabs"><Tab k="overview" label="Overview" tab={tab} setTab={setTab}/><Tab k="users" label="Users" tab={tab} setTab={setTab}/><Tab k="servers" label="Services" tab={tab} setTab={setTab}/><Tab k="plans" label="Plans" tab={tab} setTab={setTab}/><Tab k="infrastructure" label="Infrastructure" tab={tab} setTab={setTab}/><Tab k="templates" label="Templates" tab={tab} setTab={setTab}/></div></div>
   {tab==='overview'?<Audit overview={overview}/>:tab==='users'?<div className="adminDataGrid">{users.map(u=><UserRow key={u.id} u={u} update={updateUser} moderate={moderate} remove={removeUser}/>)}{!users.length&&<div className="emptyState">No users found.</div>}</div>:tab==='servers'?<div className="adminDataGrid">{servers.map(s=><div className="adminDataRow" key={s.id}><div><b>{s.name}</b><small>{s.identifier}:{s.primary_port} · {s.status}</small></div><div>{s.owner_email}<small>{s.node_name||'No node'}</small></div><div>{s.cpu_limit} CPU · {Math.round(s.memory_mb/1024)} GB<small>{s.billing_status}</small></div><div className="adminActionGroup"><button className={`btn ${s.suspended?'indigo':'rose'}`} onClick={()=>lifecycle(s,s.suspended?'unsuspend':'suspend')}>{s.suspended?<PlayCircle size={13}/>:<PauseCircle size={13}/>} {s.suspended?'Unsuspend':'Suspend'}</button><button className="btn" onClick={()=>migrate(s)}><ArrowRightLeft size={13}/>Migrate</button><button className="btn" onClick={()=>transfer(s)}>Transfer</button></div></div>)}{!servers.length&&<div className="emptyState">No managed services.</div>}</div>:tab==='plans'?<Plans plans={plans} draft={draft} setDraft={setDraft} templates={templates} createPlan={createPlan} savePlan={savePlan} removePlan={removePlan}/>:tab==='infrastructure'?<Infrastructure data={infra} drain={drain}/>:<Templates templates={templates} addTemplate={addTemplate}/>} 
  </section>
 </>
}
function Audit({overview}:{overview:any}){return <div className="adminAudit">{overview.audit?.length?overview.audit.map((a:any)=><div className="adminAuditRow" key={a.id}><span><b>{a.event}</b><small>{a.email||'system'} · {a.subject_type||'system'} {a.subject_id||''}</small></span><small>{new Date(a.created_at).toLocaleString()}</small></div>):<div className="emptyState">No audit events yet.</div>}</div>}
function Plans({plans,draft,setDraft,templates,createPlan,savePlan,removePlan}:{plans:P[];draft:any;setDraft:(v:any)=>void;templates:any[];createPlan:()=>void;savePlan:(p:P)=>void;removePlan:(p:P)=>void}){const set=(k:string,v:any)=>setDraft({...draft,[k]:v});return <div><div className="adminPlanCreate"><div className="panelSectionHead"><div><h2>Create hosting plan</h2><p>New enabled plans appear automatically in the public catalog.</p></div><button className="btn indigo" onClick={createPlan}><Plus size={13}/>Create plan</button></div><div className="adminPlanFields"><input placeholder="slug" value={draft.slug} onChange={e=>set('slug',e.target.value)}/><input placeholder="Plan name" value={draft.name} onChange={e=>set('name',e.target.value)}/><input placeholder="Description" value={draft.description} onChange={e=>set('description',e.target.value)}/><select value={draft.template_slug} onChange={e=>set('template_slug',e.target.value)}>{templates.filter(t=>t.enabled).map(t=><option key={t.slug} value={t.slug}>{t.name} · {t.slug}</option>)}</select><label>RAM MB<input type="number" value={draft.memory_mb} onChange={e=>set('memory_mb',Number(e.target.value))}/></label><label>vCPU<input type="number" step="0.25" value={draft.cpu_limit} onChange={e=>set('cpu_limit',Number(e.target.value))}/></label><label>Disk MB<input type="number" value={draft.disk_mb} onChange={e=>set('disk_mb',Number(e.target.value))}/></label><label>Price / 30d<input type="number" value={draft.price_monthly} onChange={e=>set('price_monthly',Number(e.target.value))}/></label><input placeholder="Currency" value={draft.currency} onChange={e=>set('currency',e.target.value)}/><label className="adminCheck"><input type="checkbox" checked={draft.featured} onChange={e=>set('featured',e.target.checked)}/>Featured</label></div></div><div className="adminPlanList">{plans.map(p=><PlanRow key={p.id} plan={p} templates={templates} save={savePlan} remove={removePlan}/>)}{!plans.length&&<div className="emptyState">No plans configured.</div>}</div></div>}
function PlanRow({plan,templates,save,remove}:{plan:P;templates:any[];save:(p:P)=>void;remove:(p:P)=>void}){const[p,setP]=useState<P>(plan);useEffect(()=>setP(plan),[plan]);const patch=(k:keyof P,v:any)=>setP({...p,[k]:v});return <div className="adminPlanRow"><div className="adminPlanTitle"><div><b>{p.name}</b><small>{p.slug} · {p.service_count||0} services · {p.order_count||0} orders</small></div><span className={`statusDot ${p.enabled?'active':'offline'}`}>{p.enabled?'PUBLISHED':'HIDDEN'}</span></div><div className="adminPlanFields compact"><input value={p.name} onChange={e=>patch('name',e.target.value)}/><input value={p.description||''} onChange={e=>patch('description',e.target.value)}/><select value={p.template_slug} onChange={e=>patch('template_slug',e.target.value)}>{templates.filter(t=>t.enabled||t.slug===p.template_slug).map(t=><option key={t.slug} value={t.slug}>{t.name} · {t.slug}</option>)}</select><label>RAM MB<input type="number" value={p.memory_mb} onChange={e=>patch('memory_mb',Number(e.target.value))}/></label><label>vCPU<input type="number" step="0.25" value={p.cpu_limit} onChange={e=>patch('cpu_limit',Number(e.target.value))}/></label><label>Disk MB<input type="number" value={p.disk_mb} onChange={e=>patch('disk_mb',Number(e.target.value))}/></label><label>Price<input type="number" value={p.price_monthly} onChange={e=>patch('price_monthly',Number(e.target.value))}/></label><input value={p.currency} onChange={e=>patch('currency',e.target.value)}/><label className="adminCheck"><input type="checkbox" checked={p.featured} onChange={e=>patch('featured',e.target.checked)}/>Featured</label><label className="adminCheck"><input type="checkbox" checked={p.enabled} onChange={e=>patch('enabled',e.target.checked)}/>Published</label></div><div className="adminActionGroup planActions"><button className="btn indigo" onClick={()=>save(p)}><Save size={13}/>Save</button><button className="btn rose" onClick={()=>remove(p)}><Trash2 size={13}/>Delete</button></div></div>}
function Templates({templates,addTemplate}:{templates:any[];addTemplate:()=>void}){return <div><div className="panelSectionHead"><div><h2>Deployment templates</h2><p>Runtime templates used by the provisioning engine.</p></div><button className="btn indigo" onClick={addTemplate}><Plus size={13}/>Add template</button></div><div className="adminDataGrid">{templates.map(t=><div className="adminDataRow" key={t.id}><div><b>{t.name}</b><small>{t.slug}</small></div><div>{t.category||'Game Servers'}<small>port {t.internal_port}</small></div><div style={{overflow:'hidden',textOverflow:'ellipsis'}}>{t.image}</div><span className={`statusDot ${t.enabled?'active':'offline'}`}>{t.enabled?'enabled':'disabled'}</span></div>)}{templates.length===0&&<div className="emptyState">No templates configured.</div>}</div></div>}
function Infrastructure({data,drain}:{data:any;drain:(n:any)=>void}){return <div className="adminDataGrid">{(data.nodes||[]).map((n:any)=><div className="adminDataRow" key={n.id}><div><b>{n.name}</b><small>{n.location||'Unassigned'} · Agent {n.agent_version||'unknown'}</small></div><div><span className={`statusDot ${String(n.health||'offline').toLowerCase()}`}>{n.health||'OFFLINE'}</span><small>{n.server_count||0} servers</small></div><div>{Number(n.used_cpu||0).toFixed(1)} / {Number(n.capacity_cpu||0)} CPU<small>{Math.round(Number(n.used_memory_mb||0)/1024)} / {Math.round(Number(n.capacity_memory_mb||0)/1024)} GB RAM</small></div><div className="adminActionGroup"><span className={`badge ${n.draining?'':'gray'}`}>{n.draining?'DRAINING':'SCHEDULING'}</span><button className="btn" onClick={()=>drain(n)}>{n.draining?'Resume':'Drain'}</button></div></div>)}{!(data.nodes||[]).length&&<div className="emptyState"><Network size={17}/> No registered nodes.</div>}<div className="releaseBox"><div className="sectionTitle">Migration queue</div>{(data.migrations||[]).length?(data.migrations||[]).map((m:any)=><div className="timelineRow" key={m.id}><span><b>{m.server_name}</b><small>{m.source_node||'unknown'} → {m.target_node||'unknown'} · {m.detail||''}</small></span><span><b>{m.progress}%</b><small>{m.status}</small></span></div>):<div className="emptyState">No migrations queued.</div>}</div></div>}
function Metric({label,value,icon}:{label:string;value:any;icon:React.ReactNode}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span>{icon}</div><strong>{value}</strong></div>}
function Tab({k,label,tab,setTab}:{k:string;label:string;tab:string;setTab:(v:string)=>void}){return <button className={`btn ${tab===k?'indigo':''}`} onClick={()=>setTab(k)}>{label}</button>}
function UserRow({u,update,moderate,remove}:{u:U;update:(u:U,r:string,c:string)=>void;moderate:(u:U)=>void;remove:(u:U)=>void}){const[role,setRole]=useState(u.role);const[credits,setCredits]=useState(u.credits);useEffect(()=>{setRole(u.role);setCredits(u.credits)},[u]);return <div className="adminDataRow userAdminRow"><div><b>{u.name}</b><small>{u.email}</small><small>{u.server_count||0} services · {u.order_count||0} active orders</small></div><div><span className={`statusDot ${u.banned_at?'offline':'active'}`}>{u.banned_at?'BANNED':'ACTIVE'}</span><small>{u.email_verified_at?'verified email':'unverified email'}</small></div><div className="adminUserEdit"><select className="select compact" value={role} onChange={e=>setRole(e.target.value)}><option>USER</option><option>RESELLER</option><option>SUPPORT</option><option>ADMIN</option></select><input className="smallInput" type="number" min="0" value={credits} onChange={e=>setCredits(e.target.value)}/></div><div className="adminActionGroup"><button className="btn" onClick={()=>update(u,role,credits)}><ShieldCheck size={13}/>Save</button><button className={`btn ${u.banned_at?'indigo':'rose'}`} onClick={()=>moderate(u)}>{u.banned_at?<UserCheck size={13}/>:<Ban size={13}/>} {u.banned_at?'Unban':'Ban'}</button><button className="btn rose" onClick={()=>remove(u)}><Trash2 size={13}/>Delete</button></div></div>}
