'use client';
import{useEffect,useState}from'react';
import{RefreshCw,Receipt,RotateCcw,Server,CheckCircle2,AlertTriangle,Loader2,WalletCards,Clock3}from'lucide-react';
type Order={id:string;status:string;amount:string;currency:string;server_name:string;template_slug:string;failure_reason:string;created_at:string;updated_at:string;customer_name:string;customer_email:string;plan_name:string;plan_slug:string;identifier:string|null;server_status:string|null;node_name:string|null;invoice_status:string;invoice_number:string|null;payment_method:string};
export default function AdminOrders(){
 const[data,setData]=useState<any>({orders:[],summary:{}}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 async function load(){setLoading(true);setMsg('');try{const r=await fetch('/api/admin/orders',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load orders');setData(d)}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function retry(o:Order){if(!confirm(`Retry provisioning for ${o.server_name}? This is allowed only for a paid order without a server.`))return;setBusy(o.id);setMsg('Retrying provisioning...');try{const r=await fetch(`/api/admin/orders/${o.id}/retry`,{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Retry failed');setMsg(`Provisioned ${d.identifier}${d.node?` on ${d.node}`:''}.`);await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 const s=data.summary||{};
 return <>
  <section className="adminOverview"><Metric icon={<Receipt size={15}/>} label="Orders" value={s.total||0}/><Metric icon={<CheckCircle2 size={15}/>} label="Active" value={s.active||0}/><Metric icon={<Clock3 size={15}/>} label="Provisioning" value={s.provisioning||0}/><Metric icon={<AlertTriangle size={15}/>} label="Failed" value={s.failed||0}/><Metric icon={<WalletCards size={15}/>} label="Paid value" value={`LKR ${Number(s.revenue||0).toLocaleString()}`}/></section>
  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2>Orders & provisioning</h2><p>Payment state, invoice state and deployment result from the production database.</p></div><button className="btn" disabled={loading} onClick={load}><RefreshCw size={13}/>{loading?'Loading':'Refresh'}</button></div>{msg&&<div className="notice">{msg}</div>}{loading?<div className="emptyState">Loading customer orders...</div>:<div className="adminDataGrid">{(data.orders||[]).map((o:Order)=><article className="releaseBox" key={o.id}><div className="panelSectionHead"><div><h2 style={{fontSize:13}}>{o.server_name}</h2><p>{o.customer_name||'Customer'} · {o.customer_email} · {o.plan_name||o.plan_slug||o.template_slug}</p></div><div className="actions"><span className={`statusDot ${statusClass(o.status)}`}>{o.status}</span><span className={`statusDot ${o.invoice_status==='PAID'?'active':'unknown'}`}>invoice {o.invoice_status}</span></div></div><div className="adminOverview"><Mini label="Amount" value={`${o.currency} ${Number(o.amount).toLocaleString()}`}/><Mini label="Payment" value={o.payment_method||'internal'}/><Mini label="Server" value={o.identifier||'Not provisioned'}/><Mini label="Node" value={o.node_name||'Unassigned'}/><Mini label="Invoice" value={o.invoice_number||o.invoice_status}/></div>{o.failure_reason&&<div className="notice error" style={{marginTop:12}}><AlertTriangle size={13}/> {o.failure_reason}</div>}<div className="panelSectionHead" style={{margin:'13px 0 0'}}><div><p>Order {o.id.slice(0,8)} · {new Date(o.created_at).toLocaleString()}</p></div><div className="actions">{o.identifier&&<a className="btn" href={`/servers/${o.identifier}`}><Server size={13}/>Open server</a>}{!o.identifier&&['FAILED','PAID'].includes(o.status)&&<button className="btn indigo" disabled={!!busy||o.invoice_status!=='PAID'} onClick={()=>retry(o)}>{busy===o.id?<Loader2 size={13}/>:<RotateCcw size={13}/>}Retry provisioning</button>}</div></div></article>)}{!(data.orders||[]).length&&<div className="emptyState">No orders yet.</div>}</div>}</section>
 </>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:any}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span>{icon}</div><strong>{value}</strong></div>}
function Mini({label,value}:{label:string;value:any}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span></div><strong style={{fontSize:15}}>{value}</strong></div>}
function statusClass(v:any){const s=String(v||'unknown').toLowerCase();return ['running','active','online','offline','failed','suspended','provisioning','starting'].includes(s)?s:'unknown'}
