'use client';
import {useEffect,useState}from'react';import {Archive,Plus,RefreshCw,RotateCcw,Download,Loader2,ShieldCheck}from'lucide-react';
type B={id:string;name:string;status:string;size_bytes:number;created_at:string};
export default function BackupManager({id}:{id:string}){const[data,setData]=useState<B[]>([]);const[busy,setBusy]=useState('');const[msg,setMsg]=useState('');const[loading,setLoading]=useState(true);
async function load(silent=false){if(!silent)setLoading(true);try{const r=await fetch(`/api/servers/${id}/backups`,{cache:'no-store'});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Failed to load backups');setData(d.backups||[])}catch(e:any){setMsg(e.message)}finally{if(!silent)setLoading(false)}}
useEffect(()=>{void load();const t=setInterval(()=>void load(true),10000);return()=>clearInterval(t)},[id]);
async function create(){setBusy('create');setMsg('Creating compressed backup on CrakNode...');try{const r=await fetch(`/api/servers/${id}/backups`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Backup failed');setMsg('Backup completed successfully.');await load(true)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
async function restore(b:B){if(!confirm(`Restore ${b.name}?\n\nThe current server data will be replaced with this backup and the server may restart.`))return;setBusy(b.id);setMsg(`Restoring ${b.name}...`);try{const r=await fetch(`/api/servers/${id}/backups/${b.id}/restore`,{method:'POST'});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Restore failed');setMsg('Backup restored successfully. Refresh the console if the server is restarting.');await load(true)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
function download(b:B){window.location.href=`/api/servers/${id}/backups/${b.id}/download`}
const ready=data.filter(x=>x.status==='READY').length;return <div className="card backupCardV24"><div className="fileToolbar"><div><div className="sectionTitle">Server Backups</div><div className="small">Real CrakNode snapshots · {ready}/{data.length} ready</div></div><div className="actions"><button className="btn" disabled={loading} onClick={()=>load()}><RefreshCw size={14}/>Refresh</button><button className="btn indigo" disabled={!!busy} onClick={create}>{busy==='create'?<Loader2 className="spin" size={14}/>:<Plus size={14}/>} {busy==='create'?'Creating...':'Create Backup'}</button></div></div>{msg&&<div className={`notice ${/failed|error/i.test(msg)?'error':''}`}>{msg}</div>}<div className="list">{loading?<div className="emptyState"><Loader2 className="spin" size={18}/> Loading backups...</div>:data.length===0?<div className="backupEmptyV24"><ShieldCheck size={26}/><b>No backups yet</b><span>Create your first server snapshot before making risky changes.</span></div>:data.map(b=><div className="listItem backupRowV24" key={b.id}><div className="backupIdentity"><span className="backupIconV24"><Archive size={17}/></span><div><b>{b.name}</b><div className="small">{new Date(b.created_at).toLocaleString()} · {format(b.size_bytes||0)}</div></div></div><div className="actions"><span className={`badge ${b.status==='READY'?'':'gray'}`}>{b.status}</span>{b.status==='READY'&&<><button className="btn" disabled={!!busy} onClick={()=>download(b)}><Download size={13}/>Download</button><button className="btn orange" disabled={!!busy} onClick={()=>restore(b)}>{busy===b.id?<Loader2 className="spin" size={13}/>:<RotateCcw size={13}/>} {busy===b.id?'Restoring...':'Restore'}</button></>}</div></div>)}</div></div>}
async function safeJson(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {error:t||`HTTP ${r.status}`}}}
function format(n:number){return n>1073741824?`${(n/1073741824).toFixed(2)} GB`:n>1048576?`${(n/1048576).toFixed(1)} MB`:n>1024?`${(n/1024).toFixed(1)} KB`:`${n} B`}
