'use client';
import Link from'next/link';
import{useEffect,useState}from'react';
import{CreditCard,Receipt,Server,Wallet,History,ShoppingCart,ShieldCheck,ArrowUpRight}from'lucide-react';

export default function BillingManager(){
 const[plans,setPlans]=useState<any[]>([]),[history,setHistory]=useState<any>({credits:0,wallet:[],invoices:[]}),[orders,setOrders]=useState<any[]>([]),[msg,setMsg]=useState('');
 async function load(){setMsg('');try{const[p,h,o]=await Promise.all([fetch('/api/plans',{cache:'no-store'}),fetch('/api/billing/history',{cache:'no-store'}),fetch('/api/billing/orders',{cache:'no-store'})]);const[pd,hd,od]=await Promise.all([p.json(),h.json(),o.json()]);if(!p.ok)throw new Error(pd.error||'Unable to load plans');if(!h.ok)throw new Error(hd.error||'Unable to load billing history');if(!o.ok)throw new Error(od.error||'Unable to load orders');setPlans(pd.plans||[]);setHistory(hd);setOrders(od.orders||[])}catch(e:any){setMsg(e.message||'Billing data unavailable')}}
 useEffect(()=>{void load()},[]);
 const active=orders.filter((o:any)=>o.status==='ACTIVE').length,paidInvoices=(history.invoices||[]).filter((i:any)=>i.status==='PAID').length;
 return <>
  <section className="billingHero"><div className="heroCopy"><div className="eyebrow">BILLING & SERVICES</div><h1>Wallet, invoices and <span>orders</span></h1><p>Real account balance, payment history and provisioned services in one place.</p></div><div className="heroActions"><button className="btn" onClick={load}>Refresh</button><Link href="/checkout" className="btn indigo"><ShoppingCart size={14}/>Order server</Link></div></section>
  {msg&&<div className="notice error panelSection">{msg}</div>}
  <section className="billingOverview panelSection"><div className="walletSurface"><span>AVAILABLE WALLET BALANCE</span><strong>LKR {Number(history.credits||0).toLocaleString()}</strong><div className="small" style={{marginTop:8}}>Used for wallet checkout and service charges recorded by CrakHost.</div></div><Metric label="Active orders" value={active} hint={`${orders.length} total`} icon={<Server size={15}/>}/><Metric label="Paid invoices" value={paidInvoices} hint={`${history.invoices?.length||0} total`} icon={<Receipt size={15}/>}/></section>

  <section className="panelSection"><div className="panelSectionHead"><div><h2>Hosting plans</h2><p>Choose a plan, then configure the server in checkout.</p></div></div><div className="planGrid">{plans.map((p:any)=><article className="planCard" key={p.id}><div className="planName">{p.name}</div><div className="planPrice">{p.currency} {Number(p.price_monthly).toLocaleString()} <small>/ 30 days</small></div><div className="planSpecs"><div className="planSpec"><span>Memory</span><b>{Math.round(Number(p.memory_mb||0)/1024)} GB</b></div><div className="planSpec"><span>CPU</span><b>{Number(p.cpu_limit||0)} vCPU</b></div><div className="planSpec"><span>Disk</span><b>{Math.round(Number(p.disk_mb||0)/1024)} GB</b></div></div><Link className="btn indigo" style={{width:'100%',justifyContent:'center'}} href={`/checkout?plan=${encodeURIComponent(p.slug)}`}>Configure plan <ArrowUpRight size={13}/></Link></article>)}{plans.length===0&&<div className="nodeEmpty">No enabled plans are available.</div>}</div></section>

  <section className="panelSection"><div className="twoCol"><div className="card"><div className="panelSectionHead"><div><h2><Receipt size={14}/> Invoices</h2><p>Actual invoice records for this account.</p></div></div><div className="timelineList">{history.invoices?.length?history.invoices.map((i:any)=><div className="timelineRow" key={i.id}><span><b>{i.number||'Invoice'}</b><small>{i.description||'Service invoice'} · {i.created_at?new Date(i.created_at).toLocaleString():''}</small></span><span style={{textAlign:'right'}}><b>{i.currency} {Number(i.amount).toLocaleString()}</b><small>{i.status}</small></span></div>):<div className="emptyState">No invoices yet.</div>}</div></div><div className="card"><div className="panelSectionHead"><div><h2><Wallet size={14}/> Wallet activity</h2><p>Credits and debits recorded by the billing engine.</p></div></div><div className="timelineList">{history.wallet?.length?history.wallet.map((w:any)=><div className="timelineRow" key={w.id}><span><b>{w.description||'Wallet transaction'}</b><small>{w.created_at?new Date(w.created_at).toLocaleString():''}</small></span><b className={Number(w.amount)>=0?'amountPositive':'amountNegative'}>{Number(w.amount)>0?'+':''}{Number(w.amount).toLocaleString()}</b></div>):<div className="emptyState">No wallet transactions yet.</div>}</div></div></div></section>

  <section className="panelSection"><div className="card"><div className="panelSectionHead"><div><h2><History size={14}/> Order timeline</h2><p>Provisioning state linked to your hosting orders.</p></div></div><div className="timelineList">{orders.length?orders.map((o:any)=><div className="timelineRow" key={o.id}><span><b>{o.plan_name||o.server_name||'Hosting order'}</b><small>{o.identifier||o.server_name||'Pending server'} · {o.created_at?new Date(o.created_at).toLocaleString():''}</small></span><span className={`statusDot ${statusClass(o.status)}`}>{o.status||'unknown'}</span></div>):<div className="emptyState"><ShieldCheck size={18}/> No orders yet.</div>}</div></div></section>
 </>
}
function Metric({label,value,hint,icon}:{label:string;value:any;hint:string;icon:React.ReactNode}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span>{icon}</div><strong>{value}</strong><small>{hint}</small></div>}
function statusClass(v:any){const s=String(v||'unknown').toLowerCase();return ['running','active','online','offline','failed','suspended','provisioning','starting'].includes(s)?s:'unknown'}
