'use client';
import{useEffect,useMemo,useState}from'react';
import{Database,Plus,Trash2,Copy,Eye,EyeOff,RefreshCw,Activity,KeyRound,PlugZap,HardDrive,Users,Gauge,Clock3,ServerCog,FileClock,Rows3}from'lucide-react';

type DbTelemetry={reachable?:boolean;sizeBytes?:number;connections?:number;connectionLimit?:number;commits?:number;rollbacks?:number;cacheHitPct?:number;tempFiles?:number;tempBytes?:number;deadlocks?:number;rowsReturned?:number;rowsFetched?:number;rowsInserted?:number;rowsUpdated?:number;rowsDeleted?:number;statsReset?:string|null;lastActivityAt?:string|null;error?:string;sessions?:any[]};
type ManagedDb={id:string;name:string;database_name?:string;username:string;host:string;port:number;engine:string;status:string;created_at:string;telemetry?:DbTelemetry};
export default function DatabaseManager({id}:{id:string}){
 const[list,setList]=useState<ManagedDb[]>([]),[msg,setMsg]=useState(''),[name,setName]=useState('minecraft'),[creds,setCreds]=useState<any>(null),[show,setShow]=useState(false),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[tests,setTests]=useState<Record<string,any>>({}),[lastRefresh,setLastRefresh]=useState<string>('');
 async function load(showLoader=true){if(showLoader)setLoading(true);try{const r=await fetch(`/api/servers/${id}/databases`,{cache:'no-store'}),d=await safeJson(r);if(r.ok){setList(Array.isArray(d.databases)?d.databases:[]);setLastRefresh(d.refreshedAt||new Date().toISOString())}else setMsg(d.error||'Unable to load databases')}catch{setMsg('Database service is unreachable.')}finally{if(showLoader)setLoading(false)}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(false),15000);return()=>clearInterval(t)},[id]);
 async function add(){const label=name.trim();if(!/^[a-zA-Z0-9_-]{1,32}$/.test(label)){setMsg('Database label may contain only letters, numbers, _ and -.');return}setBusy('create');setMsg('Creating database...');try{const r=await fetch(`/api/servers/${id}/databases`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:label})}),d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Create failed');setCreds(d.credentials);setShow(false);setMsg('Database ready. Save the one-time credentials now.');await load(false)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 async function del(d:ManagedDb){if(!confirm(`Permanently delete database “${d.name}”? This cannot be undone.`))return;setBusy(`delete:${d.id}`);try{const r=await fetch(`/api/servers/${id}/databases?database=${encodeURIComponent(d.id)}`,{method:'DELETE'}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||'Delete failed');setMsg('Database deleted.');await load(false)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 async function action(d:ManagedDb,kind:'test'|'rotate-password'){if(kind==='rotate-password'&&!confirm(`Rotate the password for ${d.name}? Existing applications using the old password will stop connecting.`))return;setBusy(`${kind}:${d.id}`);try{const r=await fetch(`/api/servers/${id}/databases`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({databaseId:d.id,action:kind})}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||'Database action failed');if(kind==='test'){setTests(v=>({...v,[d.id]:x.result}));setMsg(`Credential + read/write verification passed in ${x.result?.latencyMs??'-'} ms.`)}else{setCreds(x.credentials);setShow(false);setMsg('Password rotated. Save the new one-time credentials now.')}await load(false)}catch(e:any){setTests(v=>({...v,[d.id]:{ok:false,error:e.message}}));setMsg(e.message)}finally{setBusy('')}}
 async function copy(v:string){try{await navigator.clipboard.writeText(v);setMsg('Copied to clipboard.')}catch{setMsg('Clipboard access was blocked by the browser.')}}
 const summary=useMemo(()=>({size:list.reduce((n,d)=>n+Number(d.telemetry?.sizeBytes||0),0),connections:list.reduce((n,d)=>n+Number(d.telemetry?.connections||0),0),healthy:list.filter(d=>d.telemetry?.reachable!==false).length,temp:list.reduce((n,d)=>n+Number(d.telemetry?.tempBytes||0),0)}),[list]);
 return <div className="card v24Manager" style={{padding:18}}><div className="fileToolbar"><div><div className="sectionTitle"><Database size={16}/> Managed PostgreSQL Pro</div><div className="small">Real PostgreSQL size, connections, cache, row activity and session telemetry. Auto-refreshes every 15 seconds.</div></div><button className="btn" disabled={loading} onClick={()=>void load()}><RefreshCw size={14}/>{loading?'Refreshing':'Refresh'}</button></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,margin:'14px 0'}}><Metric icon={<Database size={15}/>} label="Databases" value={String(list.length)}/><Metric icon={<HardDrive size={15}/>} label="Total size" value={bytes(summary.size)}/><Metric icon={<Users size={15}/>} label="Connections" value={String(summary.connections)}/><Metric icon={<FileClock size={15}/>} label="Temp I/O" value={bytes(summary.temp)}/><Metric icon={<Activity size={15}/>} label="Telemetry" value={`${summary.healthy}/${list.length||0} online`}/></div>
 <div className="consoleInput"><input value={name} maxLength={32} onChange={e=>setName(e.target.value)} placeholder="Database label" onKeyDown={e=>{if(e.key==='Enter')void add()}}/><button className="btn indigo" disabled={!!busy||!name.trim()} onClick={()=>void add()}><Plus size={14}/>{busy==='create'?'Creating...':'Create database'}</button></div>{msg&&<div className="notice">{msg}</div>}
 {creds&&<div className="credentialBox" style={{marginTop:14}}><div className="sectionTitle"><KeyRound size={15}/> One-time credentials</div><p className="small">The password is only shown after creation or rotation. Save it before leaving this page.</p>{['host','port','database','username','password','url'].map(k=><div className="rowLine" key={k}><span style={{minWidth:0}}><small>{k==='url'?'CONNECTION URL':k.toUpperCase()}</small><code style={{wordBreak:'break-all'}}>{k==='password'&&!show?'••••••••••••':k==='url'&&!show?maskUrl(String(creds[k]??'')):String(creds[k]??'')}</code></span><div className="actions">{(k==='password'||k==='url')&&<button className="iconBtn" onClick={()=>setShow(!show)}>{show?<EyeOff size={14}/>:<Eye size={14}/>}</button>}<button className="iconBtn" onClick={()=>void copy(String(creds[k]??''))}><Copy size={14}/></button></div></div>)}</div>}
 <div style={{display:'grid',gap:14,marginTop:16}}>{loading?<div className="emptyState">Loading databases...</div>:list.length?list.map(d=><DatabaseCard key={d.id} d={d} test={tests[d.id]} busy={busy} onCopy={copy} onTest={()=>action(d,'test')} onRotate={()=>action(d,'rotate-password')} onDelete={()=>del(d)}/>):<div className="emptyState">No managed databases created.</div>}</div>
 <div className="small" style={{marginTop:14,display:'flex',alignItems:'center',gap:6}}><Clock3 size={12}/> Last telemetry refresh: {lastRefresh?new Date(lastRefresh).toLocaleString():'-'}</div></div>
}
function DatabaseCard({d,test,busy,onCopy,onTest,onRotate,onDelete}:{d:ManagedDb;test:any;busy:string;onCopy:(v:string)=>Promise<void>;onTest:()=>void;onRotate:()=>void;onDelete:()=>void}){const t=d.telemetry||{};const endpoint=`${d.host}:${d.port}`;const rowWrites=Number(t.rowsInserted||0)+Number(t.rowsUpdated||0)+Number(t.rowsDeleted||0);return <section style={{border:'1px solid rgba(148,163,184,.14)',borderRadius:16,padding:16,background:'rgba(8,12,22,.48)'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div style={{minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:9,flexWrap:'wrap'}}><Database size={16}/><b style={{fontSize:17}}>{d.name}</b><span className={`runtimeBadge ${t.reachable===false?'offlineState':'onlineState'}`}>{t.reachable===false?'UNREACHABLE':d.status||'READY'}</span></div><div className="small" style={{marginTop:5}}>{d.engine} · {d.database_name||d.name}</div></div><div className="actions" style={{flexWrap:'wrap'}}><button className="btn" onClick={()=>void onCopy(endpoint)}><Copy size={13}/>Endpoint</button><button className="btn" disabled={!!busy} onClick={onTest}><PlugZap size={13}/>{busy===`test:${d.id}`?'Verifying...':'Verify login + RW'}</button><button className="btn" disabled={!!busy} onClick={onRotate}><KeyRound size={13}/>{busy===`rotate-password:${d.id}`?'Rotating...':'Rotate password'}</button><button className="iconBtn danger" disabled={!!busy} onClick={onDelete} title="Delete database"><Trash2 size={14}/></button></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(135px,1fr))',gap:9,marginTop:14}}><Metric icon={<HardDrive size={14}/>} label="Database size" value={bytes(Number(t.sizeBytes||0))}/><Metric icon={<Users size={14}/>} label="Connections" value={String(t.connections??0)}/><Metric icon={<Gauge size={14}/>} label="Conn limit" value={Number(t.connectionLimit??-1)<0?'Unlimited':String(t.connectionLimit)}/><Metric icon={<Gauge size={14}/>} label="Cache hit" value={`${Number(t.cacheHitPct??0).toFixed(2)}%`}/><Metric icon={<Activity size={14}/>} label="Transactions" value={num(Number(t.commits||0)+Number(t.rollbacks||0))}/><Metric icon={<Rows3 size={14}/>} label="Row writes" value={num(rowWrites)}/><Metric icon={<FileClock size={14}/>} label="Temp I/O" value={`${bytes(Number(t.tempBytes||0))} · ${num(Number(t.tempFiles||0))} files`}/><Metric icon={<ServerCog size={14}/>} label="Deadlocks" value={String(t.deadlocks??0)}/><Metric icon={<Clock3 size={14}/>} label="Last activity" value={timeAgo(t.lastActivityAt)}/></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:12}}><Info label="Host" value={d.host}/><Info label="Port" value={String(d.port)}/><Info label="Database" value={d.database_name||d.name}/><Info label="Username" value={d.username}/><Info label="Created" value={new Date(d.created_at).toLocaleString()}/><Info label="Stats since" value={t.statsReset?new Date(t.statsReset).toLocaleString():'PostgreSQL start'}/></div>
 {t.error&&<div className="notice" style={{marginTop:12}}>{t.error}</div>}{test&&<div className="notice" style={{marginTop:12}}>{test.ok===false?`Connection test failed: ${test.error}`:`Verified · ${test.latencyMs} ms · ${test.database} · ${test.username} · ${test.readWrite?'READ/WRITE':'READ ONLY'} · PostgreSQL ${test.server_version||String(test.version||'').replace('PostgreSQL ','')}`}</div>}
 <div style={{marginTop:14}}><div className="sectionTitle" style={{fontSize:13}}><Activity size={14}/> Live connections</div>{Array.isArray(t.sessions)&&t.sessions.length?<div style={{display:'grid',gap:7,marginTop:8}}>{t.sessions.map((s:any)=><div key={s.pid} style={{display:'grid',gridTemplateColumns:'70px 90px minmax(100px,1fr) minmax(100px,1fr) 90px',gap:8,padding:'8px 10px',borderRadius:10,background:'rgba(15,23,42,.36)',fontSize:12,alignItems:'center'}}><code>PID {s.pid}</code><b>{s.state||'unknown'}</b><span>{s.client_addr||'local'}</span><span>{s.wait_event||s.application_name||'active client'}</span><span>{timeAgo(s.query_start||s.state_change||s.backend_start)}</span></div>)}</div>:<div className="small" style={{marginTop:7}}>No active sessions right now.</div>}</div></section>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div style={{border:'1px solid rgba(148,163,184,.12)',borderRadius:12,padding:'10px 11px',background:'rgba(15,23,42,.3)'}}><div className="small" style={{display:'flex',gap:6,alignItems:'center',textTransform:'uppercase'}}>{icon}{label}</div><b style={{display:'block',fontSize:18,marginTop:5}}>{value}</b></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rowLine" style={{margin:0}}><span style={{minWidth:0}}><small>{label.toUpperCase()}</small><code style={{wordBreak:'break-all'}}>{value}</code></span><button className="iconBtn" onClick={()=>navigator.clipboard.writeText(value).catch(()=>{})}><Copy size={13}/></button></div>}
async function safeJson(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {error:t||`HTTP ${r.status}`}}}
function bytes(v:number){if(!Number.isFinite(v)||v<=0)return '0 B';const u=['B','KB','MB','GB','TB'];let n=v,i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n>=10?n.toFixed(1):n.toFixed(2)} ${u[i]}`}
function num(v:number){return new Intl.NumberFormat().format(Number.isFinite(v)?v:0)}
function timeAgo(v?:string|null){if(!v)return 'No activity';const n=new Date(v).getTime();if(!Number.isFinite(n))return '-';const s=Math.max(0,Math.floor((Date.now()-n)/1000));if(s<60)return `${s}s ago`;if(s<3600)return `${Math.floor(s/60)}m ago`;if(s<86400)return `${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`}
function maskUrl(v:string){try{const u=new URL(v);if(u.password)u.password='••••••••••••';return u.toString()}catch{return v.replace(/:\/\/([^:]+):([^@]+)@/,'://$1:••••••••••••@')}}
