'use client';
import{useEffect,useState}from'react';import{KeyRound,Webhook,Plus,Trash2,Copy,Code2,RefreshCw}from'lucide-react';
export default function DeveloperCenter(){
 const[keys,setKeys]=useState<any[]>([]),[hooks,setHooks]=useState<any[]>([]),[secret,setSecret]=useState(''),[apiToken,setApiToken]=useState(''),[msg,setMsg]=useState(''),[keyName,setKeyName]=useState('Production API'),[scopes,setScopes]=useState('servers:read,servers:write,console:read,console:write'),[hookName,setHookName]=useState('Server Events'),[hookUrl,setHookUrl]=useState('');
 async function load(){setMsg('');const[k,h]=await Promise.all([fetch('/api/developer/keys',{cache:'no-store'}),fetch('/api/developer/webhooks',{cache:'no-store'})]);const[kd,hd]=await Promise.all([k.json(),h.json()]);if(k.ok)setKeys(kd.keys||[]);else setMsg(kd.error||'Unable to load API keys');if(h.ok)setHooks(hd.webhooks||[]);else setMsg(hd.error||'Unable to load webhooks')}
 useEffect(()=>{void load()},[]);
 async function createKey(){const list=scopes.split(',').map(x=>x.trim()).filter(Boolean);if(!keyName.trim()||!list.length)return setMsg('Key name and at least one scope are required.');const r=await fetch('/api/developer/keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:keyName.trim(),scopes:list})}),d=await r.json();if(r.ok){setApiToken(d.token);setMsg('API key created. Copy it now; it will not be shown again.');void load()}else setMsg(d.error||'Failed')}
 async function revoke(id:string){const r=await fetch('/api/developer/keys',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});if(!r.ok)setMsg('Unable to revoke API key.');void load()}
 async function createHook(){if(!hookName.trim()||!hookUrl.trim())return setMsg('Webhook name and URL are required.');const r=await fetch('/api/developer/webhooks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:hookName.trim(),url:hookUrl.trim(),events:['server.status','server.suspended','invoice.paid']})}),d=await r.json();if(r.ok){setSecret(d.secret);setHookUrl('');setMsg('Webhook created. Save the signing secret now.');void load()}else setMsg(d.error||'Failed')}
 async function delHook(id:string){const r=await fetch('/api/developer/webhooks',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});if(!r.ok)setMsg('Unable to remove webhook.');void load()}
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">DEVELOPER</div><h1>API & <span>webhooks</span></h1><p>Scoped access keys and signed event destinations managed from one workspace.</p></div><div className="heroActions"><button className="btn" onClick={load}><RefreshCw size={14}/>Refresh</button></div></section>
  {msg&&<div className="notice panelSection">{msg}</div>}
  <section className="twoCol panelSection"><div className="card adminSurface"><div className="panelSectionHead"><div><h2><KeyRound size={14}/> API keys</h2><p>Create scoped bearer credentials for the CrakHost API.</p></div></div>{apiToken&&<div className="releaseBox"><div className="sectionTitle">One-time API token</div><code className="codeBlock">{apiToken}</code><button className="btn" style={{marginTop:9}} onClick={()=>navigator.clipboard.writeText(apiToken)}><Copy size={13}/>Copy token</button></div>}<div className="releaseBox"><div className="field"><label>Key name</label><input value={keyName} onChange={e=>setKeyName(e.target.value)}/></div><div className="field"><label>Scopes</label><input value={scopes} onChange={e=>setScopes(e.target.value)} placeholder="servers:read,servers:write"/></div><button className="btn indigo" onClick={createKey}><Plus size={13}/>Create key</button></div><div className="timelineList" style={{marginTop:12}}>{keys.map(k=><div className="timelineRow" key={k.id}><span><b>{k.name}</b><small>{k.token_prefix}•••• · {(k.scopes||[]).join(', ')} · {k.last_used_at?'Last used '+new Date(k.last_used_at).toLocaleString():'Never used'}</small></span><button className="iconBtn danger" onClick={()=>revoke(k.id)} title="Revoke key"><Trash2 size={14}/></button></div>)}{keys.length===0&&<div className="emptyState">No API keys.</div>}</div><div className="releaseBox"><div className="sectionTitle"><Code2 size={13}/> API examples</div><code className="codeBlock">GET /api/v1/servers{`\n`}GET /api/v1/servers/:id/stats{`\n`}GET /api/v1/servers/:id/logs{`\n`}POST /api/v1/servers/:id/action{`\n`}POST /api/v1/servers/:id/command{`\n`}Authorization: Bearer ch_...</code></div></div>
  <div className="card adminSurface"><div className="panelSectionHead"><div><h2><Webhook size={14}/> Webhooks</h2><p>Deliver selected platform events to HTTPS endpoints.</p></div></div>{secret&&<div className="releaseBox"><div className="sectionTitle">One-time signing secret</div><code className="codeBlock">{secret}</code><button className="btn" style={{marginTop:9}} onClick={()=>navigator.clipboard.writeText(secret)}><Copy size={13}/>Copy secret</button></div>}<div className="releaseBox"><div className="field"><label>Webhook name</label><input value={hookName} onChange={e=>setHookName(e.target.value)}/></div><div className="field"><label>HTTPS URL</label><input value={hookUrl} onChange={e=>setHookUrl(e.target.value)} placeholder="https://example.com/webhooks/crakhost"/></div><button className="btn indigo" onClick={createHook}><Plus size={13}/>Add webhook</button></div><div className="timelineList" style={{marginTop:12}}>{hooks.map(h=><div className="timelineRow" key={h.id}><span><b>{h.name}</b><small>{h.url} · {(h.events||[]).join(', ')}</small></span><button className="iconBtn danger" onClick={()=>delHook(h.id)} title="Delete webhook"><Trash2 size={14}/></button></div>)}{hooks.length===0&&<div className="emptyState">No webhooks configured.</div>}</div></div></section>
 </>
}
