'use client';
import {useEffect,useRef,useState} from 'react';
import {File,Folder,FolderPlus,FilePlus,Save,Trash2,ChevronLeft,RefreshCw,Upload,Download,Home,Loader2} from 'lucide-react';
type Item={name:string;path:string;type:'file'|'directory';size:number;modified:string};
export default function FileManager({id}:{id:string}){const[path,setPath]=useState('/'),[items,setItems]=useState<Item[]>([]),[editing,setEditing]=useState<string|null>(null),[content,setContent]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0);const inputRef=useRef<HTMLInputElement>(null);
async function load(p=path){setLoading(true);setMsg('');try{const r=await fetch(`/api/servers/${id}/files?path=${encodeURIComponent(p)}`,{cache:'no-store'});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Unable to load files');setItems(d.items||[]);setPath(d.path||p)}catch(e:any){setMsg(e.message||'Unable to load files')}finally{setLoading(false)}}
useEffect(()=>{void load('/')},[id]);
async function readFile(p:string){const r=await fetch(`/api/servers/${id}/files?mode=read&path=${encodeURIComponent(p)}`,{cache:'no-store'});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'This file cannot be opened in the text editor. Download it instead.');return String(d.content||'')}
async function open(i:Item){if(i.type==='directory'){setEditing(null);void load(i.path);return}setMsg('');try{setEditing(i.path);setContent(await readFile(i.path))}catch(e:any){setEditing(null);setMsg(e.message)}}
async function save(){if(!editing||busy)return;setBusy(true);setMsg('Saving...');try{const r=await fetch(`/api/servers/${id}/files`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({path:editing,content})});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Save failed');setMsg('Saved successfully.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
async function create(kind:'file'|'directory'){const n=prompt(kind==='directory'?'Folder name':'File name')?.trim();if(!n)return;if(n.includes('/')||n.includes('\\')){setMsg('Name cannot contain / or \\.');return}const p=(path==='/'?'':path)+'/'+n;setBusy(true);try{const r=await fetch(`/api/servers/${id}/files`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:p,kind})});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Create failed');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
async function remove(i:Item){if(!confirm(`Delete ${i.name}? This cannot be undone.`))return;setBusy(true);try{const r=await fetch(`/api/servers/${id}/files?path=${encodeURIComponent(i.path)}`,{method:'DELETE'});const d=await safeJson(r);if(!r.ok)throw new Error(d.error||'Delete failed');if(editing===i.path)setEditing(null);await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
function download(i:Item){if(i.type!=='file')return;window.location.href=`/api/servers/${id}/transfer?path=${encodeURIComponent(i.path)}`}
function upload(file:File){if(file.size>512*1024*1024){setMsg('File exceeds the 512 MB transfer limit.');return}const target=(path==='/'?'':path)+'/'+file.name;setBusy(true);setProgress(0);setMsg(`Uploading ${file.name}...`);const xhr=new XMLHttpRequest();xhr.open('PUT',`/api/servers/${id}/transfer?path=${encodeURIComponent(target)}`);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};xhr.onerror=()=>{setMsg('Upload failed: network error');setBusy(false);setProgress(0)};xhr.onload=async()=>{let d:any={};try{d=JSON.parse(xhr.responseText||'{}')}catch{}if(xhr.status>=200&&xhr.status<300){setMsg(`Uploaded ${file.name} (${formatBytes(file.size)}).`);await load()}else setMsg(d.error||`Upload failed (HTTP ${xhr.status})`);setBusy(false);setProgress(0)};xhr.send(file)}
const up=()=>{if(path==='/')return;void load(path.split('/').slice(0,-1).join('/')||'/')};
return <div className="fileManager"><div className="card fileCardV24"><div className="fileToolbar"><div className="pathBar"><button className="iconBtn" title="Root" onClick={()=>load('/')}><Home size={15}/></button><button className="iconBtn" disabled={path==='/'||loading} onClick={up}><ChevronLeft size={16}/></button><code>{path}</code></div><div className="actions"><input ref={inputRef} type="file" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/><button className="btn" disabled={busy} onClick={()=>inputRef.current?.click()}><Upload size={14}/>{busy&&progress>0?`${progress}%`:'Upload File'}</button><button className="btn" disabled={loading} onClick={()=>load()}><RefreshCw size={14}/>Refresh</button><button className="btn" disabled={busy} onClick={()=>create('directory')}><FolderPlus size={14}/>Folder</button><button className="btn indigo" disabled={busy} onClick={()=>create('file')}><FilePlus size={14}/>File</button></div></div>{busy&&progress>0&&<div className="uploadProgress"><span style={{width:`${progress}%`}}/></div>}{msg&&<div className={`notice ${/failed|error|cannot|exceeds/i.test(msg)?'error':''}`}>{msg}</div>}<div className="fileTable"><div className="fileRow fileHead"><b>Name</b><b>Size</b><b>Modified</b><b></b></div>{loading?<div className="emptyState"><Loader2 className="spin" size={18}/> Loading files...</div>:items.length===0?<div className="emptyState">This directory is empty.</div>:items.map(i=><div className="fileRow" key={i.path}><button className="fileNameBtn" onClick={()=>open(i)}>{i.type==='directory'?<Folder size={16}/>:<File size={16}/>}<span>{i.name}</span></button><span>{i.type==='directory'?'—':formatBytes(i.size)}</span><span>{i.modified?new Date(i.modified).toLocaleString():'—'}</span><span className="actions">{i.type==='file'&&<button className="iconBtn" title="Download file" onClick={()=>download(i)}><Download size={14}/></button>}<button className="iconBtn danger" disabled={busy} title="Delete" onClick={()=>remove(i)}><Trash2 size={14}/></button></span></div>)}</div></div>{editing&&<div className="card editorCard"><div className="editorTop"><div><div className="sectionTitle">Text Editor</div><code>{editing}</code></div><button className="btn indigo" disabled={busy} onClick={save}><Save size={14}/>{busy?'Saving...':'Save'}</button></div><textarea className="codeEditor" value={content} onChange={e=>setContent(e.target.value)} spellCheck={false}/></div>}</div>}
async function safeJson(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {error:t||`HTTP ${r.status}`}}}
function formatBytes(n:number){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`}
