'use client';
import{useEffect,useState}from'react';import{Activity,Boxes,Database,RefreshCw,Server,ArrowRightLeft}from'lucide-react';
export default function InfrastructureCenter(){
 const[d,setD]=useState<any>({nodes:[],dbHosts:[],migrations:[],summary:{}}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(silent=false){if(!silent)setLoading(true);try{const r=await fetch('/api/admin/infrastructure',{cache:'no-store'});const x=await r.json();if(!r.ok)throw new Error(x.error||'Infrastructure request failed');setD(x);setError('')}catch(e:any){setError(e.message)}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(()=>load(true),15000);return()=>clearInterval(t)},[]);
 const s=d.summary||{};return <div className="stack"><div className="pageHeader"><div><div className="eyebrow">INFRASTRUCTURE</div><h1>Infrastructure Center</h1><p className="muted">Live compute health, capacity, database hosts and server movement.</p></div><button className="btn" onClick={()=>load()} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/>Refresh</button></div>
 {error&&<div className="notice error">{error}</div>}
 <div className="infraHealthGrid"><div className="infraHealthCard"><span>Online nodes</span><strong>{s.online||0}</strong></div><div className="infraHealthCard"><span>Degraded / Offline</span><strong>{Number(s.degraded||0)+Number(s.offline||0)}</strong></div><div className="infraHealthCard"><span>Managed servers</span><strong>{s.servers||0}</strong></div><div className="infraHealthCard"><span>Allocated memory</span><strong>{Math.round(Number(s.memoryUsedMb||0)/1024)} GB</strong></div></div>
 <div className="card"><div className="fileToolbar"><div><div className="cardTitle">Compute Fleet</div><div className="small">Heartbeat state and allocated capacity · refreshes every 15 seconds</div></div><Boxes size={18}/></div><div className="infraNodeList">{d.nodes?.length?d.nodes.map((n:any)=><div className="infraNodeRow" key={n.id}><div><b>{n.name}</b><small>{n.location} · heartbeat {n.heartbeat_age_seconds==null?'unknown':`${n.heartbeat_age_seconds}s ago`}</small></div><div className="infraResource"><strong>{Number(n.used_cpu||0).toFixed(1)} / {Number(n.capacity_cpu||0).toFixed(1)}</strong>CPU allocated</div><div className="infraResource"><strong>{Math.round(Number(n.used_memory_mb||0)/1024)} / {Math.round(Number(n.capacity_memory_mb||0)/1024)} GB</strong>Memory</div><div className="infraResource"><strong>{Math.round(Number(n.used_disk_mb||0)/1024)} / {Math.round(Number(n.capacity_disk_mb||0)/1024)} GB</strong>Disk</div><span className={`healthPill ${String(n.health||'offline').toLowerCase()}`}>{n.health||'OFFLINE'}</span></div>):<div className="emptyState">No compute nodes registered.</div>}</div></div>
 <div className="twoCol"><div className="card"><div className="fileToolbar"><div><div className="cardTitle">Database Hosts</div><div className="small">Real database host registry</div></div><Database size={17}/></div>{d.dbHosts?.length?d.dbHosts.map((h:any)=><div className="listRow" key={h.id}><div><b>{h.name}</b><div className="small">{h.engine} · {h.host}:{h.port}</div></div><span className={`badge ${h.enabled?'':'gray'}`}>{h.enabled?'ENABLED':'DISABLED'}</span></div>):<div className="emptyState">No database hosts configured.</div>}</div><div className="card"><div className="fileToolbar"><div><div className="cardTitle">Migration Activity</div><div className="small">Recent server movement jobs</div></div><ArrowRightLeft size={17}/></div>{d.migrations?.length?d.migrations.slice(0,8).map((m:any)=><div className="listRow" key={m.id}><div><b>{m.server_name}</b><div className="small">{m.source_node||'source'} → {m.target_node||'target'}</div></div><span className={`badge ${m.status==='FAILED'?'gray':''}`}>{m.status}</span></div>):<div className="emptyState">No migration jobs yet.</div>}</div></div>
 <div className="card"><div className="fileToolbar"><div><div className="cardTitle">Scheduling State</div><div className="small">Capacity-aware placement uses enabled, healthy and non-draining nodes.</div></div><Activity size={17}/></div><div className="listRow"><div><b>Draining nodes</b><div className="small">Excluded from new deployments</div></div><strong>{s.draining||0}</strong></div><div className="listRow"><div><b>Database hosts</b><div className="small">Registered backing services</div></div><strong>{d.dbHosts?.length||0}</strong></div><div className="listRow"><div><b>Recent migrations</b><div className="small">Tracked transfer jobs</div></div><strong>{d.migrations?.length||0}</strong></div></div>
 </div>
}
