'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {AtSign,CheckCircle2,Copy,ExternalLink,Globe2,Inbox,KeyRound,Mail,Network,Plus,RefreshCw,Send,Server,ShieldCheck,Trash2,TriangleAlert} from 'lucide-react';

type Domain={id:string;domain:string;hostname:string;dkim_selector:string;enabled:boolean;is_primary:boolean;created_at:string;updated_at:string};
type Mailbox={id:string;domain_id:string;email:string;local_part:string;display_name:string;quota_mb:number;enabled:boolean;domain:string};
type Alias={id:string;domain_id:string;source:string;destination:string;enabled:boolean;domain:string};
type Probe={ok:boolean;latencyMs:number;error?:string};
type Snapshot={domains:Domain[];mailboxes:Mailbox[];aliases:Alias[];runtime:{hostname:string;publicIp:string;webmailUrl:string;services:{smtp25:Probe;submission587:Probe;imaps993:Probe}};dns:Array<{type:string;name:string;value:string;purpose:string}>;dkimReady:boolean};

export default function MailHostingCenter(){
 const[data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[port25,setPort25]=useState<{ok:boolean;host:string;latencyMs:number;error?:string}|null>(null);
 const[domain,setDomain]=useState(''),[hostname,setHostname]=useState(''),[selector,setSelector]=useState('mail');
 const[mailDomain,setMailDomain]=useState(''),[localPart,setLocalPart]=useState(''),[displayName,setDisplayName]=useState(''),[password,setPassword]=useState(''),[quota,setQuota]=useState(1024);
 const[aliasDomain,setAliasDomain]=useState(''),[aliasLocal,setAliasLocal]=useState(''),[aliasTarget,setAliasTarget]=useState('');
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/mail/hosting',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load CrakMail');setData(d);if(!mailDomain&&d.domains?.[0])setMailDomain(d.domains[0].id);if(!aliasDomain&&d.domains?.[0])setAliasDomain(d.domains[0].id)}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function act(action:string,payload:any={}){setBusy(action);setMsg('');try{const r=await fetch('/api/admin/mail/hosting',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})}),d=await r.json();if(!r.ok)throw new Error(d.error||'CrakMail operation failed');if(d.domains)setData(d);return d}catch(e:any){setMsg(e.message);throw e}finally{setBusy('')}}
 const primary=useMemo(()=>data?.domains.find(d=>d.is_primary)||data?.domains[0]||null,[data]);
 function copy(v:string){void navigator.clipboard.writeText(v);setMsg('Copied to clipboard.');setTimeout(()=>setMsg(''),1200)}
 async function saveDomain(){const d=domain.trim().toLowerCase();const h=(hostname.trim()||`mail.${d}`).toLowerCase();await act('saveDomain',{domain:d,hostname:h,dkimSelector:selector,isPrimary:true});setDomain('');setHostname('');setMsg('Mail domain saved. CrakMail will generate its DKIM key after the mail service starts.');await load()}
 async function createMailbox(){await act('createMailbox',{domainId:mailDomain,localPart,displayName,password,quotaMb:quota});setLocalPart('');setDisplayName('');setPassword('');setMsg('Mailbox created. IMAP/SMTP login uses the full email address.');await load()}
 async function createAlias(){await act('createAlias',{domainId:aliasDomain,localPart:aliasLocal,destination:aliasTarget});setAliasLocal('');setAliasTarget('');setMsg('Alias saved.');await load()}
 async function probe(){setBusy('probePort25');setMsg('Testing outbound TCP/25 from the panel container...');try{const d=await act('probePort25');setPort25(d);setMsg(d.ok?`Outbound port 25 is reachable (${d.latencyMs} ms).`:`Outbound port 25 test failed: ${d.error||'connection failed'}`)}catch{}finally{setBusy('')}}
 const services=data?.runtime.services;
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">CRAKMAIL · SELF-HOSTED MAIL</div><h1>Mail hosting <span>control plane</span></h1><p>Run your own Postfix + Dovecot/SASL mail host, manage mailboxes and aliases, publish SPF/DKIM/DMARC, and use webmail without an external SMTP provider.</p></div><div className="heroActions"><Link href="/admin/mail" className="btn"><Mail size={14}/>SMTP Templates</Link><button className="btn" onClick={()=>load()} disabled={loading}><RefreshCw size={14}/>{loading?'Loading':'Refresh'}</button></div></section>
  {msg&&<div className={`notice panelSection ${/failed|error|invalid|required|blocked|unreachable|not found/i.test(msg)?'error':''}`}>{msg}</div>}
  <section className="adminOverview panelSection"><Metric label="Domains" value={data?.domains.length??'—'}/><Metric label="Mailboxes" value={data?.mailboxes.length??'—'}/><Metric label="Aliases" value={data?.aliases.length??'—'}/><Metric label="DKIM" value={data?.dkimReady?'Ready':primary?'Pending':'—'}/><Metric label="Mail host" value={data?.runtime.hostname||primary?.hostname||'Not configured'}/></section>

  <section className="twoCol panelSection">
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2><Globe2 size={15}/> Domain setup</h2><p>Add the domain once here. DNS values are generated below from the live CrakMail configuration.</p></div></div>
    <div className="formGrid"><div className="field"><label>Mail domain</label><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="example.com"/></div><div className="field"><label>Mail hostname</label><input value={hostname} onChange={e=>setHostname(e.target.value)} placeholder={domain?`mail.${domain}`:'mail.example.com'}/></div><div className="field"><label>DKIM selector</label><input value={selector} onChange={e=>setSelector(e.target.value)} placeholder="mail"/></div></div>
    <button className="btn indigo" disabled={!!busy||!domain.trim()} onClick={saveDomain}><Plus size={14}/>{busy==='saveDomain'?'Saving':'Add / update primary domain'}</button>
    <div className="timelineList" style={{marginTop:16}}>{data?.domains.map(d=><div className="timelineRow" key={d.id}><span><b>{d.domain}</b><small>{d.hostname} · DKIM {d.dkim_selector}{d.is_primary?' · primary':''}</small></span><span className={`statusDot ${d.enabled?'active':'unknown'}`}>{d.enabled?'enabled':'disabled'}</span></div>)}{!data?.domains.length&&<div className="emptyState">No mail domain configured yet.</div>}</div>
   </div>
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2><Network size={15}/> Port & service health</h2><p>Internal listeners prove the stack is running. The outbound port-25 test checks whether this VPS can open SMTP connections to the public internet.</p></div></div>
    <div className="timelineList"><ServiceRow label="SMTP 25" probe={services?.smtp25}/><ServiceRow label="Submission 587" probe={services?.submission587}/><ServiceRow label="IMAPS 993" probe={services?.imaps993}/></div>
    <button className="btn indigo" style={{marginTop:14}} onClick={probe} disabled={!!busy}><Send size={14}/>{busy==='probePort25'?'Testing':'Test outbound port 25'}</button>
    {port25&&<div className="releaseBox" style={{marginTop:14}}><div className="sectionTitle">Port 25 result</div><p className="small">Target: {port25.host}:25</p><p className="small">Result: <b>{port25.ok?'REACHABLE':'FAILED'}</b> · {port25.latencyMs} ms {port25.error?`· ${port25.error}`:''}</p></div>}
   </div>
  </section>

  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2><ShieldCheck size={15}/> DNS & deliverability records</h2><p>Publish these records at your DNS provider. PTR/reverse DNS must be set at the VPS provider.</p></div><span className={`statusDot ${data?.dkimReady?'active':'unknown'}`}>{data?.dkimReady?'DKIM ready':'DKIM pending'}</span></div>
   <div className="timelineList">{data?.dns.map((r,i)=><div className="timelineRow" key={`${r.type}-${r.name}-${i}`}><span style={{minWidth:0}}><b>{r.type} · {r.name}</b><small>{r.purpose}</small><code style={{display:'block',whiteSpace:'pre-wrap',wordBreak:'break-all',marginTop:5}}>{r.value}</code></span><button className="btn" onClick={()=>copy(r.value)}><Copy size={12}/>Copy</button></div>)}{!data?.dns.length&&<div className="emptyState">Add a primary mail domain to generate DNS records.</div>}</div>
   <div className="releaseBox" style={{marginTop:14}}><div className="sectionTitle"><TriangleAlert size={13}/> Required for good delivery</div><p className="small">A/MX + SPF + DKIM + DMARC should resolve publicly, and the VPS IP PTR should point back to the same mail hostname. For this VPS, also verify outbound port 25 before enabling direct internet delivery.</p></div>
  </section>

  <section className="twoCol panelSection">
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2><Inbox size={15}/> Create mailbox</h2><p>Passwords are stored as salted SSHA512 hashes for Dovecot; plaintext passwords are never stored.</p></div></div>
    <div className="formGrid"><div className="field"><label>Domain</label><select className="select" value={mailDomain} onChange={e=>setMailDomain(e.target.value)}><option value="">Select domain</option>{data?.domains.filter(d=>d.enabled).map(d=><option key={d.id} value={d.id}>{d.domain}</option>)}</select></div><div className="field"><label>Mailbox name</label><input value={localPart} onChange={e=>setLocalPart(e.target.value)} placeholder="support"/></div><div className="field"><label>Display name</label><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="CrakHost Support"/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="12+ characters" autoComplete="new-password"/></div><div className="field"><label>Quota (MB)</label><input type="number" min="64" max="102400" value={quota} onChange={e=>setQuota(Number(e.target.value))}/></div></div>
    <button className="btn indigo" disabled={!!busy||!mailDomain||!localPart.trim()||password.length<12} onClick={createMailbox}><Plus size={14}/>Create mailbox</button>
   </div>
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2><AtSign size={15}/> Create alias</h2><p>v0.47 aliases forward only to an enabled local mailbox to avoid unsafe open-forwarding behaviour.</p></div></div>
    <div className="formGrid"><div className="field"><label>Domain</label><select className="select" value={aliasDomain} onChange={e=>setAliasDomain(e.target.value)}><option value="">Select domain</option>{data?.domains.filter(d=>d.enabled).map(d=><option key={d.id} value={d.id}>{d.domain}</option>)}</select></div><div className="field"><label>Alias name</label><input value={aliasLocal} onChange={e=>setAliasLocal(e.target.value)} placeholder="billing"/></div><div className="field"><label>Deliver to mailbox</label><select className="select" value={aliasTarget} onChange={e=>setAliasTarget(e.target.value)}><option value="">Select mailbox</option>{data?.mailboxes.filter(m=>m.enabled).map(m=><option key={m.id} value={m.email}>{m.email}</option>)}</select></div></div>
    <button className="btn indigo" disabled={!!busy||!aliasDomain||!aliasLocal.trim()||!aliasTarget} onClick={createAlias}><Plus size={14}/>Save alias</button>
   </div>
  </section>

  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2><KeyRound size={15}/> Mailboxes</h2><p>Users sign in to webmail, IMAP and SMTP submission with their full email address.</p></div>{data?.runtime.webmailUrl&&<a className="btn indigo" href={data.runtime.webmailUrl} target="_blank" rel="noreferrer"><ExternalLink size={13}/>Open Webmail</a>}</div>
   <div className="timelineList">{data?.mailboxes.map(m=><div className="timelineRow" key={m.id}><span><b>{m.email}</b><small>{m.display_name||'No display name'} · quota {m.quota_mb} MB</small></span><div className="actions"><button className="btn" onClick={async()=>{await act('useLocalSmtp',{fromEmail:m.email});setMsg(`${m.email} is now the CrakHost transactional sender through local CrakMail.`)}}><Send size={12}/>Use as sender</button><button className="btn" onClick={async()=>{await act('updateMailbox',{id:m.id,enabled:!m.enabled});await load()}}>{m.enabled?<TriangleAlert size={12}/>:<CheckCircle2 size={12}/>} {m.enabled?'Disable':'Enable'}</button><button className="btn danger" onClick={async()=>{if(!confirm(`Delete ${m.email}? Stored mail files are not automatically erased by this database action.`))return;await act('deleteMailbox',{id:m.id});await load()}}><Trash2 size={12}/>Delete</button></div></div>)}{!data?.mailboxes.length&&<div className="emptyState">No mailboxes yet.</div>}</div>
  </section>

  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2>Aliases</h2><p>Local forwarding addresses managed by Postfix virtual alias maps.</p></div></div><div className="timelineList">{data?.aliases.map(a=><div className="timelineRow" key={a.id}><span><b>{a.source}</b><small>→ {a.destination}</small></span><button className="btn danger" onClick={async()=>{await act('deleteAlias',{id:a.id});await load()}}><Trash2 size={12}/>Delete</button></div>)}{!data?.aliases.length&&<div className="emptyState">No aliases yet.</div>}</div></section>

  <section className="twoCol panelSection"><div className="card adminSurface"><div className="panelSectionHead"><div><h2><Server size={15}/> Client settings</h2></div></div><div className="releaseBox"><p className="small"><b>IMAP:</b> {data?.runtime.hostname||primary?.hostname||'mail.example.com'} · 993 · SSL/TLS</p><p className="small"><b>SMTP:</b> {data?.runtime.hostname||primary?.hostname||'mail.example.com'} · 587 · STARTTLS</p><p className="small"><b>Username:</b> full email address</p></div></div><div className="card adminSurface"><div className="panelSectionHead"><div><h2><Mail size={15}/> Webmail</h2><p>Roundcube Elastic is reverse-proxied through your existing host Nginx.</p></div></div><p className="small">Expected URL: {data?.runtime.webmailUrl||`https://${primary?.hostname||'mail.example.com'}`}</p>{data?.runtime.webmailUrl&&<a className="btn indigo" href={data.runtime.webmailUrl} target="_blank" rel="noreferrer"><ExternalLink size={13}/>Open webmail</a>}</div></section>
 </>
}
function Metric({label,value}:{label:string;value:any}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span></div><strong style={{fontSize:15}}>{String(value)}</strong></div>}
function ServiceRow({label,probe}:{label:string;probe?:Probe}){return <div className="timelineRow"><span><b>{label}</b><small>{probe?`${probe.latencyMs} ms${probe.error?` · ${probe.error}`:''}`:'not checked'}</small></span><span className={`statusDot ${probe?.ok?'active':'offline'}`}>{probe?.ok?'online':'offline'}</span></div>}
