'use client';
import {useEffect,useState} from 'react';
import {CheckCircle2,Copy,Mail,RefreshCw,Save,Send,ShieldCheck} from 'lucide-react';

type Settings={enabled:boolean;host:string;port:number;encryption:'STARTTLS'|'SSL_TLS'|'NONE';username:string;passwordConfigured:boolean;fromName:string;fromEmail:string;replyTo:string;rejectUnauthorized:boolean;logoUrl:string;updatedAt?:string|null};
type Template={key:string;name:string;description:string;subject:string;html_body:string;text_body:string;variables:string[];enabled:boolean;system_template:boolean;updated_at?:string};
type Log={id:number;template_key:string|null;recipient:string;subject:string;status:string;message_id:string;error:string;created_at:string};
const defaultLogo='https://i.ibb.co/pv5zb3Q5/logo-Photoroom.png';
const blank:Settings={enabled:false,host:'',port:587,encryption:'STARTTLS',username:'',passwordConfigured:false,fromName:'CrakHost',fromEmail:'',replyTo:'',rejectUnauthorized:true,logoUrl:defaultLogo};
const automations=[
 ['New registration','email_verification'],['Verified account','welcome'],['Forgot password','password_reset_otp'],['Password changed','password_changed'],
 ['Invoice due','invoice_due'],['Invoice paid','invoice_paid'],['Automatic refund','payment_refunded'],['Server provisioned','server_ready'],['Support staff reply','support_reply']
];

export default function MailCenter(){
 const[settings,setSettings]=useState<Settings>(blank),[password,setPassword]=useState(''),[clearPassword,setClearPassword]=useState(false),[templates,setTemplates]=useState<Template[]>([]),[selected,setSelected]=useState(''),[draft,setDraft]=useState<Template|null>(null),[logs,setLogs]=useState<Log[]>([]),[testTo,setTestTo]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 async function load(){setLoading(true);setMsg('');try{const r=await fetch('/api/admin/mail',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load mail center');setSettings({...blank,...d.settings});setTemplates(d.templates||[]);setLogs(d.logs||[]);const key=selected||(d.templates?.[0]?.key||'');setSelected(key);const t=(d.templates||[]).find((x:Template)=>x.key===key)||d.templates?.[0]||null;setDraft(t?{...t}:null)}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function choose(key:string){setSelected(key);const t=templates.find(x=>x.key===key)||null;setDraft(t?{...t}:null);setMsg('')}
 async function saveSettings(){setBusy('settings');setMsg('Saving SMTP configuration...');try{const r=await fetch('/api/admin/mail',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...settings,password,clearPassword})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save SMTP settings');setSettings({...blank,...d.settings});setTemplates(d.templates||templates);setLogs(d.logs||logs);setPassword('');setClearPassword(false);setMsg('SMTP configuration and email branding saved securely.')}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 async function sendTest(){setBusy('test');setMsg('Sending SMTP test...');try{const r=await fetch('/api/admin/mail/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({to:testTo})}),d=await r.json();if(!r.ok)throw new Error(d.error||'SMTP test failed');setMsg(`Test email sent${d.messageId?` · ${d.messageId}`:''}.`);await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 async function saveTemplate(){if(!draft)return;setBusy('template');setMsg('Saving email template...');try{const r=await fetch('/api/admin/mail/templates',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({key:draft.key,name:draft.name,description:draft.description,subject:draft.subject,htmlBody:draft.html_body,textBody:draft.text_body,enabled:draft.enabled})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save template');setTemplates(x=>x.map(t=>t.key===d.template.key?d.template:t));setDraft({...d.template});setMsg('Email template saved.')}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 const status=settings.enabled?'Enabled':'Disabled';
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">MAIL DELIVERY</div><h1>SMTP & <span>email templates</span></h1><p>Configure outbound mail, branding, automatic account emails, billing notifications and delivery history from the admin control plane.</p></div><div className="heroActions"><button className="btn" onClick={()=>load()} disabled={loading}><RefreshCw size={14}/>{loading?'Loading':'Refresh'}</button></div></section>
  {msg&&<div className={`notice panelSection ${/failed|error|invalid|required|unable|disabled/i.test(msg)?'error':''}`}>{msg}</div>}
  <section className="adminOverview panelSection"><Metric label="Mail delivery" value={status}/><Metric label="SMTP host" value={settings.host||'Not configured'}/><Metric label="Encryption" value={settings.encryption}/><Metric label="Templates" value={templates.length}/><Metric label="Recent sent" value={logs.filter(x=>x.status==='SENT').length}/></section>

  <section className="twoCol panelSection">
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2><Mail size={15}/> SMTP configuration</h2><p>The SMTP password is encrypted at rest with the server session secret and is never returned to the browser.</p></div><span className={`statusDot ${settings.enabled?'active':'unknown'}`}>{status}</span></div>
    <label className="checkLine"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings(x=>({...x,enabled:e.target.checked}))}/>Enable outbound email</label>
    <div className="formGrid"><div className="field"><label>SMTP host</label><input value={settings.host} onChange={e=>setSettings(x=>({...x,host:e.target.value}))} placeholder="smtp.example.com"/></div><div className="field"><label>Port</label><input type="number" min="1" max="65535" value={settings.port} onChange={e=>setSettings(x=>({...x,port:Number(e.target.value)}))}/></div><div className="field"><label>Encryption</label><select className="select" value={settings.encryption} onChange={e=>setSettings(x=>({...x,encryption:e.target.value as Settings['encryption']}))}><option value="STARTTLS">STARTTLS (587)</option><option value="SSL_TLS">SSL/TLS (465)</option><option value="NONE">None</option></select></div><div className="field"><label>SMTP username</label><input value={settings.username} onChange={e=>setSettings(x=>({...x,username:e.target.value}))} autoComplete="off"/></div><div className="field"><label>SMTP password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={settings.passwordConfigured?'Stored securely · leave blank to keep':'Enter SMTP password'} autoComplete="new-password"/></div><div className="field"><label>Sender name</label><input value={settings.fromName} onChange={e=>setSettings(x=>({...x,fromName:e.target.value}))}/></div><div className="field"><label>Sender email</label><input type="email" value={settings.fromEmail} onChange={e=>setSettings(x=>({...x,fromEmail:e.target.value}))} placeholder="noreply@example.com"/></div><div className="field"><label>Reply-to</label><input type="email" value={settings.replyTo} onChange={e=>setSettings(x=>({...x,replyTo:e.target.value}))} placeholder="support@example.com"/></div><div className="field" style={{gridColumn:'1 / -1'}}><label>Brand logo URL</label><input value={settings.logoUrl} onChange={e=>setSettings(x=>({...x,logoUrl:e.target.value}))} placeholder={defaultLogo}/></div></div>
    <label className="checkLine"><input type="checkbox" checked={settings.rejectUnauthorized} onChange={e=>setSettings(x=>({...x,rejectUnauthorized:e.target.checked}))}/>Verify SMTP TLS certificate</label>
    {settings.passwordConfigured&&<label className="checkLine"><input type="checkbox" checked={clearPassword} onChange={e=>setClearPassword(e.target.checked)}/>Clear stored SMTP password on save</label>}
    <div className="actions"><button className="btn indigo" onClick={saveSettings} disabled={!!busy}><Save size={14}/>{busy==='settings'?'Saving':'Save SMTP settings'}</button></div>
   </div>
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2><Send size={15}/> Brand & test</h2><p>Every transactional HTML email is wrapped in the CrakHost branded email frame automatically.</p></div></div><div className="releaseBox" style={{textAlign:'center',marginBottom:16}}>{settings.logoUrl?<img src={settings.logoUrl} alt="CrakHost email logo" style={{maxWidth:210,maxHeight:72,objectFit:'contain'}}/>:<span>No logo configured</span>}</div><div className="field"><label>Test recipient</label><input type="email" value={testTo} onChange={e=>setTestTo(e.target.value)} placeholder="you@example.com"/></div><button className="btn indigo" onClick={sendTest} disabled={!!busy||!testTo.trim()}><Send size={14}/>{busy==='test'?'Sending':'Send SMTP test'}</button><div className="releaseBox" style={{marginTop:14}}><div className="sectionTitle"><ShieldCheck size={13}/> Security notes</div><p className="small">Use port 587 with STARTTLS or port 465 with SSL/TLS when your provider supports it. Keep TLS certificate verification enabled in production.</p><p className="small">Changing SESSION_SECRET after saving the SMTP password makes the encrypted password unreadable; enter the SMTP password again after such a rotation.</p></div></div>
  </section>

  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2><CheckCircle2 size={15}/> Transactional automations</h2><p>These events send automatically when their template and SMTP delivery are enabled.</p></div></div><div className="adminOverview">{automations.map(([event,key])=><div className="surfaceMetric" key={key}><div className="surfaceMetricTop"><span>{event}</span></div><strong style={{fontSize:13}}><code>{key}</code></strong></div>)}</div></section>

  <section className="twoCol panelSection"><div className="card adminSurface"><div className="panelSectionHead"><div><h2>Email templates</h2><p>System templates are editable without changing application code.</p></div></div><div className="ticketList">{templates.map(t=><button type="button" key={t.key} className={`ticketCard ${selected===t.key?'active':''}`} onClick={()=>choose(t.key)}><span><b>{t.name}</b><small>{t.description}</small></span><span className={`statusDot ${t.enabled?'active':'unknown'}`}>{t.enabled?'enabled':'disabled'}</span></button>)}{!templates.length&&<div className="emptyState">Run the mail migrations to create the default templates.</div>}</div></div>
   <div className="card adminSurface">{draft?<><div className="panelSectionHead"><div><h2>{draft.name}</h2><p>Template key: <code>{draft.key}</code></p></div><label className="checkLine"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft(x=>x?{...x,enabled:e.target.checked}:x)}/>Enabled</label></div><div className="field"><label>Template name</label><input value={draft.name} onChange={e=>setDraft(x=>x?{...x,name:e.target.value}:x)}/></div><div className="field"><label>Description</label><input value={draft.description} onChange={e=>setDraft(x=>x?{...x,description:e.target.value}:x)}/></div><div className="field"><label>Subject</label><input value={draft.subject} onChange={e=>setDraft(x=>x?{...x,subject:e.target.value}:x)}/></div><div className="releaseBox"><div className="sectionTitle">Available variables</div><div className="actions">{(draft.variables||[]).map(v=><button type="button" className="btn" key={v} onClick={()=>navigator.clipboard.writeText(`{{${v}}}`)}><Copy size={12}/>{`{{${v}}}`}</button>)}</div></div><div className="field"><label>HTML body</label><textarea className="wideInput" style={{minHeight:220,fontFamily:'monospace'}} value={draft.html_body} onChange={e=>setDraft(x=>x?{...x,html_body:e.target.value}:x)}/></div><div className="field"><label>Plain-text body</label><textarea className="wideInput" style={{minHeight:150,fontFamily:'monospace'}} value={draft.text_body} onChange={e=>setDraft(x=>x?{...x,text_body:e.target.value}:x)}/></div><button className="btn indigo" onClick={saveTemplate} disabled={!!busy}><Save size={14}/>{busy==='template'?'Saving':'Save template'}</button></>:<div className="emptyState">Select a template.</div>}</div>
  </section>

  <section className="card adminSurface panelSection"><div className="panelSectionHead"><div><h2>Delivery log</h2><p>Latest 50 mail attempts. SMTP credentials are never written to this log.</p></div></div><div className="timelineList">{logs.map(l=><div className="timelineRow" key={l.id}><span><b>{l.subject||l.template_key||'Email'}</b><small>{l.recipient} · {l.template_key||'direct'} · {new Date(l.created_at).toLocaleString()}{l.error?` · ${l.error}`:''}</small></span><span className={`statusDot ${l.status==='SENT'?'active':l.status==='FAILED'?'offline':'unknown'}`}>{l.status}</span></div>)}{!logs.length&&<div className="emptyState">No email delivery attempts yet.</div>}</div></section>
 </>
}
function Metric({label,value}:{label:string;value:any}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span></div><strong style={{fontSize:15}}>{String(value)}</strong></div>}
