'use client';
import{useEffect,useMemo,useState}from'react';
import{Boxes,Plus,RefreshCw,Cpu,MemoryStick,HardDrive,Activity,Power,PauseCircle,PlayCircle,Loader2}from'lucide-react';

type Form={name:string;location:string;baseUrl:string;token:string;memoryMb:number;diskMb:number;cpu:number};
const empty:Form={name:'',location:'',baseUrl:'',token:'',memoryMb:0,diskMb:0,cpu:0};
export default function NodeManager(){
 const[nodes,setNodes]=useState<any[]>([]),[summary,setSummary]=useState<any>({}),[policy,setPolicy]=useState<any>({}),[msg,setMsg]=useState(''),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[f,setF]=useState<Form>(empty);
 function set(k:keyof Form,v:any){setF(x=>({...x,[k]:v}))}
 async function load(silent=false){if(!silent)setLoading(true);try{const r=await fetch('/api/admin/infrastructure',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed to load nodes');setNodes(d.nodes||[]);setSummary(d.summary||{});setPolicy(d.provisioningPolicy||{});setMsg('')}catch(e:any){setMsg(e.message||'Failed to load nodes')}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(()=>load(true),15000);return()=>clearInterval(t)},[]);
 async function add(){setBusy('add');setMsg('Testing CrakNode and registering...');try{const r=await fetch('/api/nodes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Node registration failed');setMsg(`Node registered · agent ${d.health?.version||'unknown'}`);setShow(false);setF(empty);await load(true)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 async function drain(n:any){const key=`drain:${n.id}`;setBusy(key);try{const r=await fetch(`/api/admin/nodes/${n.id}/drain`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({draining:!n.draining})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Drain update failed');await load(true)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 async function toggle(n:any){const key=`toggle:${n.id}`;setBusy(key);try{const r=await fetch(`/api/admin/nodes/${n.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:!n.enabled})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Node update failed');await load(true)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 const states=useMemo(()=>({online:Number(summary.online||0),degraded:Number(summary.degraded||0),offline:Number(summary.offline||0),draining:Number(summary.draining||0),servers:Number(summary.servers||0)}),[summary]);
 const gb=(mb:any)=>Number.isFinite(Number(mb))?`${(Number(mb)/1024).toFixed(1)} GB`:'—';
 return <>
  <div className="pageHead"><div><p>INFRASTRUCTURE</p><h1>Compute Nodes</h1><p>Live heartbeat, backing storage, host pressure and scheduling controls for every CrakNode.</p></div><div className="actions"><button className="btn" onClick={()=>load()} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/>Refresh</button><button className="btn indigo" onClick={()=>setShow(v=>!v)}><Plus size={14}/>Manual Node</button></div></div>
  <div className="nodeSummary"><div className="nodeSummaryCard"><span>Online</span><strong>{states.online}</strong></div><div className="nodeSummaryCard"><span>Degraded</span><strong>{states.degraded}</strong></div><div className="nodeSummaryCard"><span>Offline</span><strong>{states.offline}</strong></div><div className="nodeSummaryCard"><span>Draining</span><strong>{states.draining}</strong></div><div className="nodeSummaryCard"><span>Servers</span><strong>{states.servers}</strong></div></div>
  <div className="small" style={{marginTop:10}}>Provisioning disk guard: keep at least {Number(policy.minFreePercent??10)}% free and {Math.round(Number(policy.reserveMb??2048)/1024)} GB reserve; the larger reserve wins.</div>
  {msg&&<div className={`notice ${/failed|error|cannot|required|forbidden|low/i.test(msg)?'error':''}`}>{msg}</div>}
  {show&&<div className="card section"><div className="sectionTitle">Manual registration</div><p className="small" style={{marginTop:-5,marginBottom:14}}>Auto-registration is recommended. Use this only when connecting an agent manually.</p><div className="formGrid"><input value={f.name} onChange={e=>set('name',e.target.value)} placeholder="Node name"/><input value={f.location} onChange={e=>set('location',e.target.value)} placeholder="Location"/><input value={f.baseUrl} onChange={e=>set('baseUrl',e.target.value)} placeholder="https://node.example.com:8088"/><input value={f.token} onChange={e=>set('token',e.target.value)} placeholder="CrakNode API token" type="password"/><input type="number" min="1" value={f.memoryMb||''} onChange={e=>set('memoryMb',Number(e.target.value))} placeholder="Memory MB"/><input type="number" min="1" value={f.diskMb||''} onChange={e=>set('diskMb',Number(e.target.value))} placeholder="Disk MB"/><input type="number" min="1" step="0.1" value={f.cpu||''} onChange={e=>set('cpu',Number(e.target.value))} placeholder="CPU capacity"/></div><button className="btn indigo" disabled={busy==='add'} onClick={add}>{busy==='add'?<Loader2 size={14} className="spin"/>:<Plus size={14}/>}Register Node</button></div>}
  {loading?<div className="nodeEmpty"><Loader2 className="spin" size={24}/><div style={{marginTop:10}}>Loading live node state...</div></div>:nodes.length===0?<div className="nodeEmpty"><Boxes size={28}/><div style={{marginTop:10}}>No nodes registered. Start a CrakNode with auto-registration enabled.</div></div>:<div className="nodeGrid section">{nodes.map(n=>{
   const health=String(n.health||(!n.enabled?'DISABLED':'OFFLINE')).toUpperCase();const cls=health.toLowerCase();const util=n.utilization||{};const heartbeat=n.heartbeat_age_seconds==null?'No heartbeat':`${n.heartbeat_age_seconds}s ago`;const rt=n.runtime||null;
   const meter=(label:string,icon:any,pct:number,value:string)=>{const Icon=icon;return <div className="nodeMeter"><div className="nodeMeterHead"><span><Icon size={11} style={{verticalAlign:'middle'}}/> {label}</span><b>{value}</b></div><div className="nodeBar"><span style={{width:`${Math.max(0,Math.min(100,Number(pct||0)))}%`}}/></div></div>};
   return <article className="nodeCard" key={n.id}><div className="nodeCardTop"><div className="nodeIdentity"><div className="nodeIcon"><Boxes size={20}/></div><div><h3>{n.name}</h3><p>{n.location||'Unspecified location'}</p></div></div><span className={`healthPill ${cls}`}>{health}</span></div><div className="nodeMeta"><span><Activity size={11}/> heartbeat {heartbeat}</span><span>agent {n.agent_version||'unknown'}</span><span>{Number(n.server_count||0)} servers</span>{n.draining&&<span>draining</span>}</div><div className="nodeMeters">{meter('CPU',Cpu,util.cpuPct,`${Number(n.used_cpu||0).toFixed(1)} / ${Number(n.capacity_cpu||0).toFixed(1)}`)}{meter('RAM',MemoryStick,util.memoryPct,`${Math.round(Number(n.used_memory_mb||0)/1024)} / ${Math.round(Number(n.capacity_memory_mb||0)/1024)} GB`)}{meter('Allocated Disk',HardDrive,util.diskPct,`${Math.round(Number(n.used_disk_mb||0)/1024)} / ${Math.round(Number(n.capacity_disk_mb||0)/1024)} GB`)}</div>{rt?.status==='online'?<div className="nodeMeta" style={{marginTop:10}}><span>pressure {String(rt.pressureLevel||'unknown')}</span><span>backing free {gb(rt.diskFreeMb)}</span><span>safe allocatable {gb(rt.safeDiskAvailableMb)}</span><span>containers {Number(rt.runningContainers||0)}/{Number(rt.managedContainers||0)}</span></div>:rt?.error?<div className="small" style={{marginTop:10,color:'#fda4af'}}>Runtime diagnostics: {rt.error}</div>:null}<div className="nodeActions"><button className="btn" disabled={!!busy||!n.enabled} onClick={()=>drain(n)}>{busy===`drain:${n.id}`?<Loader2 size={14} className="spin"/>:n.draining?<PlayCircle size={14}/>:<PauseCircle size={14}/>} {n.draining?'Resume Scheduling':'Drain Scheduling'}</button><button className={n.enabled?'btn rose':'btn indigo'} disabled={!!busy} onClick={()=>toggle(n)}>{busy===`toggle:${n.id}`?<Loader2 size={14} className="spin"/>:<Power size={14}/>} {n.enabled?'Disable Node':'Enable Node'}</button></div></article>
  })}</div>}
 </>
}
