'use client';
import {useEffect,useState} from 'react';
import {BellRing,Mail,Save} from 'lucide-react';

export default function NotificationSettingsPanel(){
  const[s,setS]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[recipients,setRecipients]=useState('');
  useEffect(()=>{fetch('/api/admin/notifications',{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setS(j.settings);setRecipients((j.settings.recipients||[]).join(', '))}).catch(e=>setMsg(e.message||'Notification settings unavailable'))},[]);
  async function save(){setBusy(true);setMsg('');try{const payload={...s,recipients:recipients.split(',').map(x=>x.trim()).filter(Boolean)};const r=await fetch('/api/admin/notifications',{method:'PATCH',headers:{'content-type':'application/json','x-crakhost-action':'notification-settings'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');setS(j.settings);setRecipients((j.settings.recipients||[]).join(', '));setMsg('Notification preferences saved.')}catch(e:any){setMsg(e.message||'Save failed')}finally{setBusy(false)}}
  if(!s)return <section className="card panelSection"><div className="emptyState">{msg||'Loading notification preferences…'}</div></section>;
  const numberField=(label:string,key:string,suffix='')=><div className="field"><label>{label}</label><div style={{display:'flex',alignItems:'center',gap:8}}><input type="number" value={s[key]} onChange={e=>setS({...s,[key]:Number(e.target.value)})}/>{suffix&&<small className="small">{suffix}</small>}</div></div>;
  return <section className="card panelSection"><div className="panelSectionHead"><div><h2>Alert notifications</h2><p>Turn production signals into deduplicated admin email notifications and tune the thresholds used by the Alert Center.</p></div><BellRing size={16}/></div>{msg&&<div className="notice">{msg}</div>}<div className="twoCol"><div><div className="resourceInput"><div className="resourceLabel"><Mail size={14}/>Email production alerts</div><input type="checkbox" checked={s.emailEnabled} onChange={e=>setS({...s,emailEnabled:e.target.checked})}/></div><div className="field"><label>Recipients</label><input value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder="admin@example.com, noc@example.com"/><small className="small">Leave blank to use active ADMIN account email addresses.</small></div><div className="resourceInput"><div className="resourceLabel">Critical only</div><input type="checkbox" checked={s.criticalOnly} onChange={e=>setS({...s,criticalOnly:e.target.checked})}/></div><div className="resourceInput"><div className="resourceLabel">Send resolved notifications</div><input type="checkbox" checked={s.sendResolved} onChange={e=>setS({...s,sendResolved:e.target.checked})}/></div><div className="resourceInput"><div className="resourceLabel">Suppress non-maintenance alerts during maintenance</div><input type="checkbox" checked={s.suppressDuringMaintenance} onChange={e=>setS({...s,suppressDuringMaintenance:e.target.checked})}/></div>{numberField('Repeat unresolved alert after','repeatHours','hours')}</div><div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'0 12px'}}>{numberField('Disk warning','diskWarning','%')}{numberField('Disk critical','diskCritical','%')}{numberField('Memory warning','memoryWarning','%')}{numberField('Memory critical','memoryCritical','%')}{numberField('CPU critical','cpuCritical','%')}{numberField('Stalled order','stalledOrderMinutes','min')}{numberField('Node heartbeat warning','nodeWarningSeconds','sec')}{numberField('Node offline critical','nodeCriticalSeconds','sec')}</div><button className="btn indigo" onClick={save} disabled={busy}><Save size={13}/>{busy?'Saving…':'Save notification rules'}</button></div></div></section>;
}
