'use client';
import{useEffect,useState}from'react';import{Activity,Database,RefreshCw,Server,ShieldCheck,TriangleAlert,Wrench}from'lucide-react';
export default function OperationsCenter(){
 const[d,setD]=useState<any>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/operations',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Health check failed');setD(j)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function save(){const r=await fetch('/api/admin/operations',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(d?.settings||{})});const j=await r.json();setMsg(r.ok?'Operations settings saved.':j.error||'Save failed');if(r.ok)setD((x:any)=>({...x,settings:j.settings}))}
 if(!d)return <><section className="opsHero"><div className="heroCopy"><div className="eyebrow">OPERATIONS</div><h1>Platform <span>health</span></h1><p>Running diagnostics against the panel, database and registered nodes.</p></div></section><div className="card panelSection"><div className="emptyState">{busy?'Running infrastructure diagnostics…':msg||'No diagnostics available.'}</div></div></>;
 const online=d.nodes.filter((n:any)=>n.status==='online').length;
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">OPERATIONS</div><h1>Platform <span>health</span></h1><p>Live panel, database and CrakNode diagnostics with controlled maintenance settings.</p></div><div className="heroActions"><button className="btn" onClick={load} disabled={busy}><RefreshCw size={14}/>{busy?'Checking':'Refresh'}</button></div></section>
  <section className="adminOverview panelSection"><Metric icon={<Activity size={15}/>} label="Panel" value={String(d.panel.status).toUpperCase()}/><Metric icon={<Database size={15}/>} label="Database" value={`${d.panel.databaseMs} ms`}/><Metric icon={<Server size={15}/>} label="Servers" value={d.counts.servers}/><Metric icon={<ShieldCheck size={15}/>} label="Nodes online" value={`${online}/${d.nodes.length}`}/><Metric icon={<TriangleAlert size={15}/>} label="Failed orders" value={d.counts.failed_orders}/></section>
  {msg&&<div className="notice panelSection">{msg}</div>}
  <section className="twoCol panelSection"><div className="card adminSurface"><div className="panelSectionHead"><div><h2>Node diagnostics</h2><p>Live checks returned by each enabled CrakNode.</p></div></div><div className="timelineList">{d.nodes.map((n:any)=><div className="timelineRow" key={n.id}><span><b>{n.name}</b><small>{n.location} · {n.status==='online'?`${n.latencyMs} ms · Docker ${n.dockerVersion||'unknown'}`:n.error||'Unavailable'}</small></span><span className={`statusDot ${n.status==='online'?'online':'offline'}`}>{n.status}</span></div>)}{!d.nodes.length&&<div className="emptyState">No registered nodes.</div>}</div></div><div className="card adminSurface"><div className="panelSectionHead"><div><h2><Wrench size={14}/> Maintenance control</h2><p>Settings persisted through the operations API.</p></div></div><label className="checkLine"><input type="checkbox" checked={!!d.settings.maintenanceMode} onChange={e=>setD((x:any)=>({...x,settings:{...x.settings,maintenanceMode:e.target.checked}}))}/>Maintenance mode</label><label className="field"><span>Maintenance message</span><input value={d.settings.maintenanceMessage||''} onChange={e=>setD((x:any)=>({...x,settings:{...x.settings,maintenanceMessage:e.target.value}}))}/></label><label className="field"><span>Health history retention (days)</span><input type="number" min="1" max="90" value={d.settings.healthRetentionDays||14} onChange={e=>setD((x:any)=>({...x,settings:{...x.settings,healthRetentionDays:Number(e.target.value)}}))}/></label><button className="btn indigo" onClick={save}>Save operations settings</button></div></section>
 </>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:any}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span>{icon}</div><strong>{value}</strong></div>}
