'use client';
import Link from 'next/link';
import{useEffect,useState}from'react';
import{Activity,Database,RefreshCw,Server,ShieldCheck,TriangleAlert,Wrench,Boxes,Clock3,HardDrive,Cpu,MemoryStick,RotateCcw,PackageOpen,LifeBuoy,GitBranch,Loader2}from'lucide-react';

export default function OperationsCenter(){
 const[d,setD]=useState<any>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[restarting,setRestarting]=useState('');
 async function load(silent=false){if(!silent)setBusy(true);try{const r=await fetch('/api/admin/operations',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Health check failed');setD(j);if(!silent)setMsg('')}catch(e:any){setMsg(e.message||'Health check failed')}finally{if(!silent)setBusy(false)}}
 useEffect(()=>{void load();const tick=()=>{if(!document.hidden)void load(true)};const id=window.setInterval(tick,30000);document.addEventListener('visibilitychange',tick);return()=>{window.clearInterval(id);document.removeEventListener('visibilitychange',tick)}},[]);
 async function save(){setSaving(true);try{const r=await fetch('/api/admin/operations',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(d?.settings||{})});const j=await r.json();setMsg(r.ok?'Operations settings saved.':j.error||'Save failed');if(r.ok)setD((x:any)=>({...x,settings:j.settings}))}finally{setSaving(false)}}
 async function restartService(service:string){if(!window.confirm(`Restart ${service} now?\n\nOnly this approved CrakHost service will be restarted. Customer data, databases and volumes are not removed.`))return;setRestarting(service);setMsg('');try{const r=await fetch('/api/admin/maintenance/restart',{method:'POST',headers:{'content-type':'application/json','x-crakhost-action':'restart-service'},body:JSON.stringify({service})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Service restart failed');setMsg(`${service} restarted successfully.`);await load(true)}catch(e:any){setMsg(e.message||'Service restart failed')}finally{setRestarting('')}}
 if(!d)return <><section className="opsHero"><div className="heroCopy"><div className="eyebrow">OPERATIONS</div><h1>Operations <span>command center</span></h1><p>Running diagnostics across the panel, database, host services and registered nodes.</p></div></section><div className="card panelSection"><div className="emptyState">{busy?'Running infrastructure diagnostics…':msg||'No diagnostics available.'}</div></div></>;
 const online=d.nodes.filter((n:any)=>n.status==='online').length;
 const host=d.host||{};
 const cpu=Number(host.cpu_percent||0),mem=Number(host.memory?.percent||0),disk=Number(host.disk?.percent||0);
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">OPERATIONS COMMAND CENTER</div><h1>Platform health, queue & <span>incident control</span></h1><p>Live node checks, host pressure, provisioning flow and restricted service actions from one admin workspace.</p></div><div className="heroActions"><Link className="btn" href="/nodes"><Boxes size={14}/>Nodes</Link><Link className="btn" href="/deployment"><GitBranch size={14}/>Deployments</Link><button className="btn indigo" onClick={()=>load()} disabled={busy}><RefreshCw size={14} className={busy?'spin':''}/>{busy?'Checking':'Refresh all'}</button></div></section>

  <section className="adminOverview panelSection">
   <Metric icon={<Activity size={15}/>} label="Panel" value={String(d.panel.status).toUpperCase()} hint={`v${d.panel.version}`}/>
   <Metric icon={<Database size={15}/>} label="Database" value={d.panel.databaseStatus==='online'?`${d.panel.databaseMs} ms`:'OFFLINE'} hint="Panel query latency"/>
   <Metric icon={<ShieldCheck size={15}/>} label="Nodes online" value={`${online}/${d.nodes.length}`} hint="Live diagnostic checks"/>
   <Metric icon={<PackageOpen size={15}/>} label="Provisioning queue" value={d.counts.provisioning_queue} hint="Pending · paid · provisioning"/>
   <Metric icon={<LifeBuoy size={15}/>} label="Open tickets" value={d.counts.open_tickets} hint={`${d.counts.priority_tickets} high / urgent`}/>
   <Metric icon={<TriangleAlert size={15}/>} label="Failures · 24h" value={d.counts.failed_orders_24h} hint={`${d.counts.failed_orders} total failed orders`}/>
  </section>

  {msg&&<div className={`notice panelSection ${/failed|offline|unavailable|error/i.test(msg)?'error':''}`}>{msg}</div>}
  {d.settings?.maintenanceMode&&<div className="notice panelSection"><Wrench size={14}/><span><b>Maintenance mode is enabled.</b> {d.settings.maintenanceMessage}</span></div>}

  <section className="twoCol panelSection">
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2>Host resource pressure</h2><p>Read-only VPS telemetry from the privileged updater agent.</p></div><span className={`statusDot ${host.health_status==='critical'?'failed':host.health_status==='warning'?'provisioning':'online'}`}>{host.error?'unavailable':host.health_status||'unknown'}</span></div>
    {host.error?<div className="notice error">{host.error}</div>:<div className="nodeMeters">{Meter('CPU',Cpu,`${cpu.toFixed(1)}%`,CpuIcon)}{Meter('Memory',mem,`${mem.toFixed(1)}%`,MemoryStick)}{Meter('Root disk',disk,`${disk.toFixed(1)}% · ${humanBytes(host.disk?.free_bytes)} free`,HardDrive)}</div>}
    {!host.error&&<div className="small" style={{marginTop:12}}>Uptime {humanDuration(host.uptime_seconds)} · load {Array.isArray(host.load)?host.load.join(' / '):'—'} · updater v{host.agent_version||'unknown'}</div>}
   </div>
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2><Wrench size={14}/> Maintenance control</h2><p>Global maintenance banner and health-history policy.</p></div></div><label className="checkLine"><input type="checkbox" checked={!!d.settings.maintenanceMode} onChange={e=>setD((x:any)=>({...x,settings:{...x.settings,maintenanceMode:e.target.checked}}))}/>Maintenance mode</label><label className="field"><span>Maintenance message</span><input value={d.settings.maintenanceMessage||''} onChange={e=>setD((x:any)=>({...x,settings:{...x.settings,maintenanceMessage:e.target.value}}))}/></label><label className="field"><span>Health history retention (days)</span><input type="number" min="1" max="90" value={d.settings.healthRetentionDays||14} onChange={e=>setD((x:any)=>({...x,settings:{...x.settings,healthRetentionDays:Number(e.target.value)}}))}/></label><button className="btn indigo" onClick={save} disabled={saving}>{saving?<Loader2 size={14} className="spin"/>:<ShieldCheck size={14}/>}Save operations settings</button></div>
  </section>

  <section className="card panelSection"><div className="panelSectionHead"><div><h2>Node diagnostics</h2><p>Live CrakNode connectivity, Docker state and managed workload counts.</p></div><Link href="/nodes" className="btn">Scheduling controls</Link></div><div className="timelineList">{d.nodes.map((n:any)=><div className="timelineRow" key={n.id}><span><b>{n.name}</b><small>{n.location||'Unknown location'} · agent {n.version||'unknown'} · {n.status==='online'?`${n.latencyMs} ms · Docker ${n.dockerVersion||'unknown'} · ${n.runningContainers||0}/${n.managedContainers||0} containers · ${humanBytes(n.diskFreeBytes)} free`:n.error||'Unavailable'}</small></span><span className={`statusDot ${n.status==='online'?'online':n.status==='disabled'?'suspended':'offline'}`}>{n.status}</span></div>)}{!d.nodes.length&&<div className="emptyState">No registered nodes.</div>}</div></section>

  <section className="twoCol panelSection">
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2>Provisioning queue</h2><p>Orders requiring payment, placement, provisioning or failure review.</p></div><Link href="/admin/orders" className="btn">Orders</Link></div><div className="timelineList">{d.queue?.length?d.queue.map((o:any)=><div className="timelineRow" key={o.id}><span><b>{o.server_name}</b><small>{o.customer_name} · {o.plan_name||'Custom plan'} · {o.node_name||'Awaiting node'} · {ago(o.updated_at)}</small>{o.status==='FAILED'&&o.failure_reason&&<small style={{color:'#fca5a5'}}>{o.failure_reason}</small>}</span><span className={`statusDot ${statusClass(o.status)}`}>{String(o.status).toLowerCase()}</span></div>):<div className="emptyState">Provisioning queue is clear.</div>}</div></div>
   <div className="card adminSurface"><div className="panelSectionHead"><div><h2>Recent incidents</h2><p>Offline node checks, failed provisioning and priority support events.</p></div><Clock3 size={15}/></div><div className="timelineList">{d.incidents?.length?d.incidents.map((i:any,index:number)=><div className="timelineRow" key={`${i.kind}-${i.created_at}-${index}`}><span><b>{i.title}</b><small>{String(i.kind).toUpperCase()} · {i.detail||'No detail'} · {ago(i.created_at)}</small></span><span className={`statusDot ${i.severity==='critical'?'failed':'provisioning'}`}>{i.severity}</span></div>):<div className="emptyState">No priority incidents in the current window.</div>}</div></div>
  </section>

  <section className="card panelSection"><div className="panelSectionHead"><div><h2>Node health · last 12 hours</h2><p>Hourly online-check ratio and average control-plane latency.</p></div><Activity size={15}/></div>{d.healthTimeline?.length?<div className="releaseBox">{d.healthTimeline.map((h:any)=>{const samples=Number(h.samples||0),onlineSamples=Number(h.online||0),pct=samples?onlineSamples/samples*100:0;return <div className="timelineRow" key={String(h.bucket)}><span style={{minWidth:0,flex:1}}><b>{new Date(h.bucket).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</b><small>{onlineSamples}/{samples} checks online · avg {Number(h.latency_ms||0)} ms</small><div className="fleetBar" style={{marginTop:7}}><span style={{width:`${Math.max(0,Math.min(100,pct))}%`}}/></div></span><b>{pct.toFixed(0)}%</b></div>})}</div>:<div className="emptyState">Health history will populate as diagnostics run.</div>}</section>

  <section className="card panelSection"><div className="panelSectionHead"><div><h2>Restricted service controls</h2><p>Only pre-approved stateless/control services can be restarted. Panel, PostgreSQL, Redis, volumes and arbitrary shell commands remain protected.</p></div><ShieldCheck size={15}/></div>{host.services?.length?<div className="releaseBox">{host.services.map((s:any)=><div className="timelineRow" key={`${s.service}-${s.name}`}><span><b>{s.service||s.name}</b><small>{s.status||'Unknown'} · container {s.name}</small></span><div style={{display:'flex',alignItems:'center',gap:8}}><span className={`statusDot ${serviceHealthy(s)?'online':s.state==='completed'?'suspended':'offline'}`}>{s.state||'unknown'}</span>{s.restartable&&<button className="btn" disabled={!!restarting} onClick={()=>restartService(String(s.service))}>{restarting===s.service?<Loader2 size={13} className="spin"/>:<RotateCcw size={13}/>}Restart</button>}</div></div>)}</div>:<div className="emptyState">Host service telemetry is unavailable.</div>}</section>
 </>
}

const CpuIcon=Cpu;
function Metric({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:any;hint?:string}){return <div className="surfaceMetric"><div className="surfaceMetricTop"><span>{label}</span>{icon}</div><strong>{value}</strong>{hint&&<small>{hint}</small>}</div>}
function Meter(label:string,pct:number,value:string,icon:any){const Icon=icon;return <div className="nodeMeter"><div className="nodeMeterHead"><span><Icon size={11} style={{verticalAlign:'middle'}}/> {label}</span><b>{value}</b></div><div className="nodeBar"><span style={{width:`${Math.max(0,Math.min(100,Number(pct||0)))}%`}}/></div></div>}
function humanBytes(value:any){const n0=Number(value);if(!Number.isFinite(n0)||n0<0)return'—';const u=['B','KiB','MiB','GiB','TiB'];let n=n0,i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n>=10||i===0?n.toFixed(0):n.toFixed(1)} ${u[i]}`}
function humanDuration(value:any){const n=Number(value);if(!Number.isFinite(n))return'—';const d=Math.floor(n/86400),h=Math.floor(n%86400/3600),m=Math.floor(n%3600/60);return d?`${d}d ${h}h`:h?`${h}h ${m}m`:`${m}m`}
function ago(value:any){const t=new Date(value).getTime();if(!Number.isFinite(t))return'unknown time';const s=Math.max(0,Math.round((Date.now()-t)/1000));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`}
function statusClass(v:any){const s=String(v||'').toLowerCase();return s==='failed'?'failed':s==='provisioning'||s==='paid'||s==='pending'?'provisioning':s==='active'||s==='running'?'online':'unknown'}
function serviceHealthy(s:any){return s?.state==='healthy'||String(s?.status||'').toLowerCase().startsWith('up')}
