'use client';
import {useMemo,useState} from 'react';
import {Activity,Terminal,Folder,ShieldCheck,Database,Network,Users,CalendarClock,Settings,Gamepad2,SlidersHorizontal,MapPin,Cpu,MemoryStick,HardDrive} from 'lucide-react';
import ServerControl from './ServerControl';import FileManager from './FileManager';import BackupManager from './BackupManager';import NetworkManager from './NetworkManager';import SubuserManager from './SubuserManager';import ScheduleManager from './ScheduleManager';import ServerSettings from './ServerSettings';import DatabaseManager from './DatabaseManager';import StartupManager from './StartupManager';

type Meta={name:string;address:string;nodeName:string;nodeLocation:string;nodeOnline:boolean;status:string;memoryMb:number;cpu:number;diskMb:number};
export default function ServerWorkspace({id,meta,permissions}:{id:string;meta:Meta;permissions:string[]}){
 const[tab,setTab]=useState('overview');const allowed=(p:string)=>permissions.includes('*')||permissions.includes(p);
 const tabs=useMemo(()=>[['overview',Activity,'Overview','console'],['console',Terminal,'Console','console'],['files',Folder,'Files','files'],['databases',Database,'Databases','databases'],['network',Network,'Network','network'],['backups',ShieldCheck,'Backups','backups'],['users',Users,'Users','users'],['schedules',CalendarClock,'Schedules','schedules'],['startup',SlidersHorizontal,'Startup','startup'],['settings',Settings,'Settings','settings']] as const,[]);
 const visible=tabs.filter(t=>t[0]==='overview'||allowed(t[3]));
 return <div className="serverWorkspaceV24"><section className="serverIdentityV24"><div className="serverIdentityMain"><div className="serverHeroIcon"><Gamepad2 size={25}/></div><div><div className="serverEyebrow">MANAGED INSTANCE · {id}</div><h1>{meta.name}</h1><div className="serverMetaLine"><span>{meta.address}</span><span><MapPin size={12}/>{meta.nodeLocation||meta.nodeName}</span><span className={meta.nodeOnline?'nodeLive':'nodeDown'}><i/>{meta.nodeOnline?'NODE ONLINE':'NODE OFFLINE'}</span></div></div></div><div className="serverMiniStats"><div><Cpu size={14}/><span>{meta.cpu} vCPU</span></div><div><MemoryStick size={14}/><span>{fmt(meta.memoryMb)} RAM</span></div><div><HardDrive size={14}/><span>{fmt(meta.diskMb)} Disk</span></div></div></section><div className="workspaceTabs v24Tabs">{visible.map(([k,I,l])=><button key={k} onClick={()=>setTab(k)} className={`workspaceTab ${tab===k?'active':''}`}><I size={15}/><span>{l}</span></button>)}</div><div className="workspaceBody">{(tab==='overview'||tab==='console')&&<ServerControl id={id} mode={tab}/>} {tab==='files'&&allowed('files')&&<FileManager id={id}/>} {tab==='backups'&&allowed('backups')&&<BackupManager id={id}/>} {tab==='network'&&allowed('network')&&<NetworkManager id={id}/>} {tab==='users'&&allowed('users')&&<SubuserManager id={id}/>} {tab==='schedules'&&allowed('schedules')&&<ScheduleManager id={id}/>} {tab==='startup'&&allowed('startup')&&<StartupManager id={id}/>} {tab==='settings'&&allowed('settings')&&<ServerSettings id={id}/>} {tab==='databases'&&allowed('databases')&&<DatabaseManager id={id}/>}</div></div>
}
function fmt(mb:number){if(!Number.isFinite(mb)||mb<=0)return '0 GB';return `${Number((mb/1024).toFixed(1))} GB`}
