'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Activity,CheckCircle2,ExternalLink,Globe2,Plus,RefreshCw,Save,Trash2,TriangleAlert} from 'lucide-react';

const statuses=['operational','degraded','outage','maintenance'];
export default function StatusPageManager(){
  const[data,setData]=useState<any>(null),[config,setConfig]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const[incident,setIncident]=useState({title:'',message:'',severity:'minor'});
  async function load(){setBusy(true);try{const r=await fetch('/api/admin/status-page',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Status-page settings unavailable');setData(j);setConfig(j.config);setMsg('')}catch(e:any){setMsg(e.message||'Status-page settings unavailable')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[]);
  async function save(){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/status-page',{method:'PATCH',headers:{'content-type':'application/json','x-crakhost-action':'status-page-config'},body:JSON.stringify(config)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');setConfig(j.config);setMsg('Status page settings saved.')}catch(e:any){setMsg(e.message||'Save failed')}finally{setBusy(false)}}
  async function incidentAction(action:string,payload:any={}){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/status-page',{method:'POST',headers:{'content-type':'application/json','x-crakhost-action':'status-page-incident'},body:JSON.stringify({action,...payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Incident action failed');setConfig(j.config);if(action==='create')setIncident({title:'',message:'',severity:'minor'});setMsg(`Incident ${action}d.`)}catch(e:any){setMsg(e.message||'Incident action failed')}finally{setBusy(false)}}
  function patchComponent(index:number,patch:any){setConfig((c:any)=>({...c,components:c.components.map((x:any,i:number)=>i===index?{...x,...patch}:x)}))}
  function addComponent(){const id=`custom-${Date.now()}`;setConfig((c:any)=>({...c,components:[...c.components,{id,name:'New component',source:'manual',enabled:true,manualStatus:'operational'}]}))}
  function removeComponent(index:number){setConfig((c:any)=>({...c,components:c.components.filter((_:any,i:number)=>i!==index)}))}
  if(!data||!config)return <><section className="opsHero"><div className="heroCopy"><div className="eyebrow">PUBLIC STATUS</div><h1>Uptime & <span>status page</span></h1><p>Loading public status configuration.</p></div></section><div className="card panelSection"><div className="emptyState">{busy?'Loading…':msg||'No status configuration available.'}</div></div></>;
  return <>
    <section className="opsHero"><div className="heroCopy"><div className="eyebrow">PUBLIC STATUS PAGE</div><h1>Uptime, components & <span>incidents</span></h1><p>Manage the public CrakHost availability page served at {config.domain} directly from this control panel.</p></div><div className="heroActions"><a className="btn" href={data.publicUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Open public page</a><button className="btn indigo" onClick={save} disabled={busy}><Save size={14}/>{busy?'Saving…':'Save status page'}</button></div></section>

    {msg&&<div className={msg.includes('saved')||msg.includes('created')||msg.includes('resolved')?'notice panelSection':'notice error panelSection'}>{msg}</div>}
    <section className="twoCol panelSection">
      <div className="card adminSurface"><div className="panelSectionHead"><div><h2>Public identity</h2><p>The reverse proxy keeps the public status domain separate from the private panel.</p></div><Globe2 size={16}/></div><div className="field"><label>Public domain</label><input value={config.domain} disabled/></div><div className="field"><label>Status page title</label><input value={config.title} onChange={e=>setConfig({...config,title:e.target.value})}/></div><div className="field"><label>Description</label><input value={config.description} onChange={e=>setConfig({...config,description:e.target.value})}/></div><div className="field"><label>Logo URL</label><input value={config.logoUrl||''} onChange={e=>setConfig({...config,logoUrl:e.target.value})}/></div><div className="resourceInput"><div className="resourceLabel"><Activity size={14}/>Publish status page</div><input type="checkbox" checked={config.enabled!==false} onChange={e=>setConfig({...config,enabled:e.target.checked})}/></div><div className="notice" style={{marginTop:14}}>{data.dnsNote}</div></div>
      <div className="card adminSurface"><div className="panelSectionHead"><div><h2>Public preview</h2><p>Current settings are saved in the control-plane database.</p></div><CheckCircle2 size={16}/></div><div className="releaseBox"><div className="timelineRow"><span><b>Hostname</b><small>{config.domain}</small></span><span className="statusDot online">PUBLIC</span></div><div className="timelineRow"><span><b>Refresh interval</b><small>Visitors refresh status automatically.</small></span><b>{config.refreshSeconds||30}s</b></div><div className="timelineRow"><span><b>Components</b><small>Automatic and manual services shown publicly.</small></span><b>{config.components.length}</b></div><div className="timelineRow"><span><b>Incidents</b><small>Open and recent resolved incidents.</small></span><b>{config.incidents.length}</b></div></div></div>
    </section>

    <section className="card panelSection"><div className="panelSectionHead"><div><h2>Public components</h2><p>Add services here. Automatic sources read panel/database/CrakNode health; manual services can be controlled directly.</p></div><button className="btn" onClick={addComponent}><Plus size={13}/>Add component</button></div><div className="timelineList">{config.components.map((c:any,i:number)=><div className="timelineRow" key={c.id} style={{alignItems:'flex-start'}}><div style={{display:'grid',gridTemplateColumns:'minmax(180px,1fr) minmax(180px,1fr) minmax(130px,.6fr)',gap:9,flex:1}}><div className="field" style={{margin:0}}><label>Name</label><input value={c.name} onChange={e=>patchComponent(i,{name:e.target.value})}/></div><div className="field" style={{margin:0}}><label>Source</label><select className="select" value={c.source} onChange={e=>patchComponent(i,{source:e.target.value})}><option value="panel">Control Panel</option><option value="database">Database</option><option value="nodes">All CrakNodes</option>{(data.nodes||[]).map((n:any)=><option key={n.id} value={`node:${n.id}`}>Node · {n.name}</option>)}<option value="manual">Manual</option></select></div><div className="field" style={{margin:0}}><label>Status</label><select className="select" value={c.manualStatus||'operational'} disabled={c.source!=='manual'} onChange={e=>patchComponent(i,{manualStatus:e.target.value})}>{statuses.map(x=><option value={x} key={x}>{x}</option>)}</select></div></div><div style={{display:'flex',alignItems:'center',gap:8,paddingTop:20}}><label className="statusDot online" style={{cursor:'pointer'}}><input type="checkbox" checked={c.enabled!==false} onChange={e=>patchComponent(i,{enabled:e.target.checked})}/> SHOW</label><button className="iconBtn danger" onClick={()=>removeComponent(i)} title="Remove component"><Trash2 size={15}/></button></div></div>)}</div></section>

    <section className="twoCol panelSection">
      <div className="card adminSurface"><div className="panelSectionHead"><div><h2>Publish incident</h2><p>Create public maintenance, minor degradation or major outage updates.</p></div><TriangleAlert size={16}/></div><div className="field"><label>Incident title</label><input value={incident.title} onChange={e=>setIncident({...incident,title:e.target.value})} placeholder="Network maintenance"/></div><div className="field"><label>Public message</label><textarea className="codeEditor" style={{minHeight:110,border:'1px solid var(--line)',borderRadius:10}} value={incident.message} onChange={e=>setIncident({...incident,message:e.target.value})} placeholder="What users should know…"/></div><div className="field"><label>Severity</label><select className="select" value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option value="maintenance">Maintenance</option><option value="minor">Minor incident</option><option value="major">Major outage</option></select></div><button className="btn indigo" disabled={busy||!incident.title.trim()||!incident.message.trim()} onClick={()=>incidentAction('create',incident)}><Plus size={13}/>Publish incident</button></div>
      <div className="card adminSurface"><div className="panelSectionHead"><div><h2>Incident lifecycle</h2><p>Updates are immediately visible on the public status page.</p></div><RefreshCw size={16}/></div>{config.incidents.length?<div className="releaseBox">{config.incidents.slice(0,12).map((x:any)=><div className="timelineRow" key={x.id}><span style={{minWidth:0,flex:1}}><b>{x.title}</b><small>{String(x.severity).toUpperCase()} · {String(x.status).toUpperCase()}</small></span><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{x.status!=='resolved'&&<button className="btn" disabled={busy} onClick={()=>incidentAction('resolve',{id:x.id})}>Resolve</button>}<button className="iconBtn danger" disabled={busy} onClick={()=>incidentAction('delete',{id:x.id})}><Trash2 size={14}/></button></div></div>)}</div>:<div className="emptyState">No public incidents yet.</div>}</div>
    </section>
    <section className="card panelSection"><div className="panelSectionHead"><div><h2>DNS & HTTPS</h2><p>CrakHost configures the host proxy during deployment; DNS itself remains with your DNS provider.</p></div><Globe2 size={15}/></div><div className="timelineRow"><span><b>Required DNS record</b><small>Create an A record for <code>{config.domain}</code> pointing to this VPS public IPv4. Add AAAA too only if IPv6 is routed correctly.</small></span><span className="statusDot provisioning">ONE-TIME</span></div><div className="timelineRow"><span><b>HTTPS</b><small>The deployment script can request a dedicated Let's Encrypt certificate when DNS is ready.</small></span><span className="statusDot online">AUTO</span></div></section>
  </>
}
