'use client';
import{useEffect,useState}from'react';
import{Headphones,Plus,Send,RefreshCw,XCircle,MessageSquare}from'lucide-react';
export default function SupportCenter(){
 const[tickets,setTickets]=useState<any[]>([]),[staff,setStaff]=useState(false),[active,setActive]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[subject,setSubject]=useState(''),[priority,setPriority]=useState('NORMAL'),[text,setText]=useState(''),[msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/support/tickets',{cache:'no-store'}),d=await r.json();if(r.ok){setTickets(d.tickets||[]);setStaff(!!d.staff)}else setMsg(d.error||'Failed to load tickets')}
 useEffect(()=>{void load()},[]);
 async function open(t:any){setActive(t);const r=await fetch(`/api/support/tickets/${t.id}/messages`,{cache:'no-store'}),d=await r.json();if(r.ok)setMessages(d.messages||[]);else setMsg(d.error||'Unable to load conversation')}
 async function create(){if(!subject.trim()||!text.trim())return setMsg('Subject and first message are required.');const r=await fetch('/api/support/tickets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subject,priority,message:text})}),d=await r.json();setMsg(r.ok?'Ticket created.':d.error||'Failed');if(r.ok){setSubject('');setText('');await load();if(d.ticket)await open(d.ticket)}}
 async function send(){if(!active||!text.trim())return;const r=await fetch(`/api/support/tickets/${active.id}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text})}),d=await r.json();setMsg(r.ok?'Reply sent.':d.error||'Failed');if(r.ok){setText('');await open(active);await load()}}
 async function close(){if(!active)return;const r=await fetch(`/api/support/tickets/${active.id}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status:'CLOSED'})});if(r.ok){const next={...active,status:'CLOSED'};setActive(next);setMsg('Ticket closed.');await load();await open(next)}else setMsg('Unable to close ticket.')}
 return <>
  <section className="opsHero"><div className="heroCopy"><div className="eyebrow">SUPPORT CENTER</div><h1>Help desk <span>workspace</span></h1><p>{staff?'Staff queue and customer conversations.':'Open tickets and continue conversations with support.'}</p></div><div className="heroActions"><button className="btn" onClick={load}><RefreshCw size={14}/>Refresh</button></div></section>
  {msg&&<div className="notice panelSection">{msg}</div>}
  <section className="supportShell panelSection"><div className="card supportPanel"><div className="panelSectionHead"><div><h2><Headphones size={14}/> Tickets</h2><p>{staff?'All visible support requests':'Your support requests'}</p></div><span className="badge gray">{tickets.length}</span></div><div className="ticketList">{tickets.map(t=><button className={`ticketCard ${active?.id===t.id?'active':''}`} key={t.id} onClick={()=>open(t)}><span><b>{t.subject}</b><small>{staff?t.owner_email:new Date(t.created_at).toLocaleString()} · {t.messages} messages</small></span><span style={{textAlign:'right'}}><span className={`statusDot ${t.status==='CLOSED'?'offline':'active'}`}>{t.status}</span><small>{t.priority}</small></span></button>)}{tickets.length===0&&<div className="emptyState">No support tickets.</div>}</div><div className="releaseBox"><div className="sectionTitle">Open a ticket</div><div className="field"><label>Subject</label><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What do you need help with?"/></div><div className="formGrid"><select className="select" value={priority} onChange={e=>setPriority(e.target.value)}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select><button className="btn indigo" onClick={create}><Plus size={13}/>Open ticket</button></div><textarea className="wideInput" style={{minHeight:90,resize:'vertical'}} placeholder="Describe the issue..." value={!active?text:''} onChange={e=>{if(!active)setText(e.target.value)}}/></div></div><div className="card supportPanel"><div className="panelSectionHead"><div><h2><MessageSquare size={14}/> Conversation</h2><p>{active?active.subject:'Select a ticket to view messages.'}</p></div>{active&&active.status!=='CLOSED'&&<button className="btn rose" onClick={close}><XCircle size={13}/>Close</button>}</div><div className="thread">{messages.map(m=><article className={`messageBubble ${m.staff_reply?'staff':''}`} key={m.id}><b>{m.name||'Deleted user'}</b><small>{m.staff_reply?'STAFF':'CUSTOMER'} · {new Date(m.created_at).toLocaleString()}</small><p>{m.body}</p></article>)}{!active&&<div className="emptyState">Choose a ticket from the left.</div>}{active&&messages.length===0&&<div className="emptyState">No messages in this ticket.</div>}</div>{active&&active.status!=='CLOSED'&&<div className="consoleInput" style={{marginTop:12}}><input placeholder="Write a reply..." value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}}/><button className="btn indigo" onClick={send}><Send size={13}/>Send</button></div>}</div></section>
 </>
}
