import Link from 'next/link';
import {Rocket,Gamepad2,Server,ShieldCheck,MapPin,Headphones,ArrowRight,Cpu,Zap,Activity,Database} from 'lucide-react';
import {db} from '@/lib/db';
import MarketingNav from '@/components/MarketingNav';
export const dynamic='force-dynamic';
export default async function Home(){
 const [p,n,s]=await Promise.all([db.query(`select count(*)::int count from plans where enabled=true`),db.query(`select count(*)::int count from nodes where enabled=true`),db.query(`select count(*)::int count from servers where status<>'deleted'`)]);
 const plans=Number(p.rows[0]?.count||0),nodes=Number(n.rows[0]?.count||0),servers=Number(s.rows[0]?.count||0);
 return <main className="publicRoot"><MarketingNav/>
  <section className="publicHero"><div className="publicHeroCopy"><div className="publicEyebrow"><Zap size={11}/>CRAKHOST CONTROL PLANE</div><h1>Game hosting.<br/><span>Built around real infrastructure.</span></h1><p>Deploy customer-owned game services through CrakNode with billing, live runtime controls, backups, databases, allocations and automated provisioning in one platform.</p><div className="publicHeroActions"><Link href="/games" className="publicBtn primary">Explore game hosting <ArrowRight size={14}/></Link><Link href="/login" className="publicBtn">Open client panel</Link></div></div><aside className="publicHeroPanel"><div className="publicHeroPanelHead"><span>LIVE PLATFORM</span><span className="publicLive">CONTROL PLANE ONLINE</span></div><div className="publicStatList"><div className="publicStatRow"><span>Registered nodes</span><strong>{nodes}</strong></div><div className="publicStatRow"><span>Enabled plans</span><strong>{plans}</strong></div><div className="publicStatRow"><span>Managed servers</span><strong>{servers}</strong></div><div className="publicStatRow"><span>Runtime telemetry</span><strong>CrakNode</strong></div></div></aside></section>
  <section className="publicStats"><div className="publicStat"><strong>{nodes}</strong><span>Registered Nodes</span></div><div className="publicStat"><strong>{plans}</strong><span>Enabled Plans</span></div><div className="publicStat"><strong>{servers}</strong><span>Managed Servers</span></div><div className="publicStat"><strong>Live</strong><span>Runtime Data</span></div></section>
  <section className="publicSection"><div className="publicSectionHead"><div><div className="publicEyebrow">PRODUCTS</div><h2>Choose the workload you want to run.</h2><p>The public catalog links directly into account creation, checkout and automatic provisioning.</p></div></div><div className="publicFeatureGrid"><article className="publicFeatureCard"><div className="publicFeatureIcon"><Gamepad2 size={20}/></div><h3>Game Hosting</h3><p>Minecraft and FiveM product flows with customer server workspaces.</p><Link href="/games">Explore game servers <ArrowRight size={13}/></Link></article><article className="publicFeatureCard"><div className="publicFeatureIcon"><Server size={20}/></div><h3>Cloud VPS</h3><p>VPS storefront remains clearly gated until a real virtualization backend is connected.</p><Link href="/vps">View VPS status <ArrowRight size={13}/></Link></article><article className="publicFeatureCard"><div className="publicFeatureIcon"><MapPin size={20}/></div><h3>Locations</h3><p>Public infrastructure locations are generated from enabled registered nodes.</p><Link href="/locations">View locations <ArrowRight size={13}/></Link></article></div></section>
  <section className="publicSection alt"><div className="publicSectionHead"><div><div className="publicEyebrow">CONTROL PLANE</div><h2>Hosting controls without demo counters.</h2><p>The customer interface is backed by the same billing, database and CrakNode services used for provisioning.</p></div></div><div className="publicFeatureGrid"><article className="publicFeatureCard"><div className="publicFeatureIcon"><Activity size={20}/></div><h3>Live runtime state</h3><p>Server status, CPU and memory use come from CrakNode instead of generated UI values.</p></article><article className="publicFeatureCard"><div className="publicFeatureIcon"><Database size={20}/></div><h3>Service data</h3><p>Orders, invoices, backups, databases and node capacity are stored and read from the platform database.</p></article><article className="publicFeatureCard"><div className="publicFeatureIcon"><ShieldCheck size={20}/></div><h3>Managed isolation</h3><p>Provisioned game workloads run as CrakHost-managed containers with configured resource limits.</p></article></div></section>
  <section className="publicSection"><div className="publicNotice" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}><div style={{display:'flex',gap:14,alignItems:'center'}}><Headphones size={25}/><div><b style={{color:'#fff'}}>Need help choosing a service?</b><div style={{marginTop:4}}>Open the support area or sign in to use account-linked tickets.</div></div></div><Link href="/support" className="publicBtn primary">Support <ArrowRight size={13}/></Link></div></section>
  <footer className="publicFooter"><Link className="publicBrand" href="/"><span className="publicBrandMark"><Rocket size={16}/></span><span>CRAK<b>HOST</b></span></Link><span>Hosting infrastructure powered by CrakNode.</span><div className="publicFooterLinks"><Link href="/games">Games</Link><Link href="/locations">Locations</Link><Link href="/login">Client Area</Link></div></footer>
 </main>
}
