[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid

[program:opendkim]
command=/usr/sbin/opendkim -f -x /etc/opendkim/opendkim.conf
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dovecot]
command=/usr/sbin/dovecot -F
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:postfix]
command=/usr/local/bin/crakmail-postfix-runtime
priority=30
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dkim-sync]
command=/usr/local/bin/crakmail-sync-dkim
priority=40
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
